"""Add kdv_rate column to inventory table

Revision ID: 1db2577c631f
Revises: 20251011_fix_invoices_device_id_type
Create Date: 2025-10-11 13:44:38.646606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db2577c631f'
down_revision: Union[str, None] = '20251011_fix_invoices_device_id_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip kdv_rate column modification since it already exists with correct default
    # op.alter_column('inventory', 'kdv_rate',
    #            existing_type=sa.FLOAT(),
    #            nullable=False,
    #            existing_server_default=sa.text('(20.0)'))
    
    # Skip invoices.device_id changes since they're already applied
    # op.alter_column('invoices', 'device_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_invoices_device_id'), 'invoices', ['device_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip downgrade operations since changes were applied manually
    # op.drop_index(op.f('ix_invoices_device_id'), table_name='invoices')
    # op.alter_column('invoices', 'device_id',
    #            existing_type=sa.String(length=50),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.alter_column('inventory', 'kdv_rate',
    #            existing_type=sa.FLOAT(),
    #            nullable=True,
    #            existing_server_default=sa.text('(20.0)'))
    pass
    # ### end Alembic commands ###
