"""add_is_phone_verified_to_user

Revision ID: 61f444e581bf
Revises: c838ac1e3357
Create Date: 2025-12-01 12:52:59.458918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f444e581bf'
down_revision: Union[str, None] = 'c838ac1e3357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_phone_verified')
    # ### end Alembic commands ###
