/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SubscriptionsGetCurrent200
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Get current tenant subscription and plan details
 * @summary Get current subscription details
 */
export const subscriptionsGetCurrent = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<SubscriptionsGetCurrent200>(
      {url: `/api/subscriptions/current`, method: 'GET', signal
    },
      );
    }
  



export const getSubscriptionsGetCurrentQueryKey = () => {
    return [
    `/api/subscriptions/current`
    ] as const;
    }

    
export const getSubscriptionsGetCurrentQueryOptions = <TData = Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscriptionsGetCurrentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscriptionsGetCurrent>>> = ({ signal }) => subscriptionsGetCurrent(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SubscriptionsGetCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof subscriptionsGetCurrent>>>
export type SubscriptionsGetCurrentQueryError = void


export function useSubscriptionsGetCurrent<TData = Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionsGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof subscriptionsGetCurrent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSubscriptionsGetCurrent<TData = Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscriptionsGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof subscriptionsGetCurrent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSubscriptionsGetCurrent<TData = Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get current subscription details
 */

export function useSubscriptionsGetCurrent<TData = Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscriptionsGetCurrent>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSubscriptionsGetCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




