export default {
  'x-ear-api': {
    input: {
      target: '../openapi.yaml',
    },
    output: {
      mode: 'single',
      target: './src/api/generated/xEarCRMAPIAutoGenerated.ts',
      schemas: './src/api/generated/schemas',
      client: 'axios',
      mock: false,
    },
  },
};
