/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { adminApi } from '../../apiMutator';




/**
 * Retrieve appointments information
 * @summary GET /api/reports/appointments
 */
export const reportsReportAppointments = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/appointments`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportAppointmentsQueryKey = () => {
    return [
    `/api/reports/appointments`
    ] as const;
    }

    
export const getReportsReportAppointmentsQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportAppointments>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportAppointmentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportAppointments>>> = ({ signal }) => reportsReportAppointments(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportAppointmentsQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportAppointments>>>
export type ReportsReportAppointmentsQueryError = unknown


export function useReportsReportAppointments<TData = Awaited<ReturnType<typeof reportsReportAppointments>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportAppointments>>,
          TError,
          Awaited<ReturnType<typeof reportsReportAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportAppointments<TData = Awaited<ReturnType<typeof reportsReportAppointments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportAppointments>>,
          TError,
          Awaited<ReturnType<typeof reportsReportAppointments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportAppointments<TData = Awaited<ReturnType<typeof reportsReportAppointments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary GET /api/reports/appointments
 */

export function useReportsReportAppointments<TData = Awaited<ReturnType<typeof reportsReportAppointments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportAppointments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportAppointmentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve campaigns information
 * @summary Kampanya raporu
 */
export const reportsReportCampaigns = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/campaigns`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportCampaignsQueryKey = () => {
    return [
    `/api/reports/campaigns`
    ] as const;
    }

    
export const getReportsReportCampaignsQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportCampaigns>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportCampaignsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportCampaigns>>> = ({ signal }) => reportsReportCampaigns(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportCampaignsQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportCampaigns>>>
export type ReportsReportCampaignsQueryError = unknown


export function useReportsReportCampaigns<TData = Awaited<ReturnType<typeof reportsReportCampaigns>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportCampaigns>>,
          TError,
          Awaited<ReturnType<typeof reportsReportCampaigns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportCampaigns<TData = Awaited<ReturnType<typeof reportsReportCampaigns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportCampaigns>>,
          TError,
          Awaited<ReturnType<typeof reportsReportCampaigns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportCampaigns<TData = Awaited<ReturnType<typeof reportsReportCampaigns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Kampanya raporu
 */

export function useReportsReportCampaigns<TData = Awaited<ReturnType<typeof reportsReportCampaigns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportCampaigns>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportCampaignsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve financial information
 * @summary Mali rapor
 */
export const reportsReportFinancial = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/financial`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportFinancialQueryKey = () => {
    return [
    `/api/reports/financial`
    ] as const;
    }

    
export const getReportsReportFinancialQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportFinancial>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportFinancialQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportFinancial>>> = ({ signal }) => reportsReportFinancial(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportFinancialQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportFinancial>>>
export type ReportsReportFinancialQueryError = unknown


export function useReportsReportFinancial<TData = Awaited<ReturnType<typeof reportsReportFinancial>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportFinancial>>,
          TError,
          Awaited<ReturnType<typeof reportsReportFinancial>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportFinancial<TData = Awaited<ReturnType<typeof reportsReportFinancial>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportFinancial>>,
          TError,
          Awaited<ReturnType<typeof reportsReportFinancial>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportFinancial<TData = Awaited<ReturnType<typeof reportsReportFinancial>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Mali rapor
 */

export function useReportsReportFinancial<TData = Awaited<ReturnType<typeof reportsReportFinancial>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportFinancial>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportFinancialQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve overview information
 * @summary Genel rapor özeti
 */
export const reportsReportOverview = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/overview`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportOverviewQueryKey = () => {
    return [
    `/api/reports/overview`
    ] as const;
    }

    
export const getReportsReportOverviewQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportOverview>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportOverviewQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportOverview>>> = ({ signal }) => reportsReportOverview(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportOverview>>>
export type ReportsReportOverviewQueryError = unknown


export function useReportsReportOverview<TData = Awaited<ReturnType<typeof reportsReportOverview>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportOverview>>,
          TError,
          Awaited<ReturnType<typeof reportsReportOverview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportOverview<TData = Awaited<ReturnType<typeof reportsReportOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportOverview>>,
          TError,
          Awaited<ReturnType<typeof reportsReportOverview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportOverview<TData = Awaited<ReturnType<typeof reportsReportOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Genel rapor özeti
 */

export function useReportsReportOverview<TData = Awaited<ReturnType<typeof reportsReportOverview>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportOverview>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportOverviewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve patients information
 * @summary Hasta analizi raporu
 */
export const reportsReportPatients = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/patients`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportPatientsQueryKey = () => {
    return [
    `/api/reports/patients`
    ] as const;
    }

    
export const getReportsReportPatientsQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportPatients>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportPatientsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportPatients>>> = ({ signal }) => reportsReportPatients(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportPatientsQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportPatients>>>
export type ReportsReportPatientsQueryError = unknown


export function useReportsReportPatients<TData = Awaited<ReturnType<typeof reportsReportPatients>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportPatients>>,
          TError,
          Awaited<ReturnType<typeof reportsReportPatients>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportPatients<TData = Awaited<ReturnType<typeof reportsReportPatients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportPatients>>,
          TError,
          Awaited<ReturnType<typeof reportsReportPatients>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportPatients<TData = Awaited<ReturnType<typeof reportsReportPatients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Hasta analizi raporu
 */

export function useReportsReportPatients<TData = Awaited<ReturnType<typeof reportsReportPatients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportPatients>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportPatientsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve revenue information
 * @summary GET /api/reports/revenue
 */
export const reportsReportRevenue = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/reports/revenue`, method: 'GET', signal
    },
      );
    }
  



export const getReportsReportRevenueQueryKey = () => {
    return [
    `/api/reports/revenue`
    ] as const;
    }

    
export const getReportsReportRevenueQueryOptions = <TData = Awaited<ReturnType<typeof reportsReportRevenue>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsReportRevenueQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsReportRevenue>>> = ({ signal }) => reportsReportRevenue(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ReportsReportRevenueQueryResult = NonNullable<Awaited<ReturnType<typeof reportsReportRevenue>>>
export type ReportsReportRevenueQueryError = unknown


export function useReportsReportRevenue<TData = Awaited<ReturnType<typeof reportsReportRevenue>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportRevenue>>,
          TError,
          Awaited<ReturnType<typeof reportsReportRevenue>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportRevenue<TData = Awaited<ReturnType<typeof reportsReportRevenue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsReportRevenue>>,
          TError,
          Awaited<ReturnType<typeof reportsReportRevenue>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useReportsReportRevenue<TData = Awaited<ReturnType<typeof reportsReportRevenue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary GET /api/reports/revenue
 */

export function useReportsReportRevenue<TData = Awaited<ReturnType<typeof reportsReportRevenue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsReportRevenue>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getReportsReportRevenueQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




