/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OcrInitDatabaseBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Initialize OCR service database and create required tables
 * @summary Initialize database and create tables
 */
export const ocrInitDatabase = (
    ocrInitDatabaseBody?: OcrInitDatabaseBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/init-db`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ocrInitDatabaseBody, signal
    },
      );
    }
  


export const getOcrInitDatabaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrInitDatabase>>, TError,{data: OcrInitDatabaseBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ocrInitDatabase>>, TError,{data: OcrInitDatabaseBody}, TContext> => {

const mutationKey = ['ocrInitDatabase'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ocrInitDatabase>>, {data: OcrInitDatabaseBody}> = (props) => {
          const {data} = props ?? {};

          return  ocrInitDatabase(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OcrInitDatabaseMutationResult = NonNullable<Awaited<ReturnType<typeof ocrInitDatabase>>>
    export type OcrInitDatabaseMutationBody = OcrInitDatabaseBody
    export type OcrInitDatabaseMutationError = unknown

    /**
 * @summary Initialize database and create tables
 */
export const useOcrInitDatabase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrInitDatabase>>, TError,{data: OcrInitDatabaseBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ocrInitDatabase>>,
        TError,
        {data: OcrInitDatabaseBody},
        TContext
      > => {

      const mutationOptions = getOcrInitDatabaseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    