extends: ["spectral:oas"]

rules:
  # OpenAPI linting rules
  oas3-valid-media-example: warn
  oas3-valid-schema-example: warn
  
  # Disable noisy rules for development
  operation-operationId: warn
  operation-description: warn
  info-contact: off
  info-license: off
  contact-properties: off
  license-url: off
