import React, { useState, useEffect } from 'react';
import { Button, Input, Select, Badge } from '@x-ear/ui-web';
import { Card, CardContent } from '@x-ear/ui-web';
import { useToastHelpers } from '@x-ear/ui-web';
import { Upload, Eye, Download, Trash2, FileText, X, AlertCircle, CheckCircle, Clock, Search } from 'lucide-react';

// API imports
import { getXEarCRMAPIAutoGenerated } from '../../api/generated/xEarCRMAPIAutoGenerated';

interface Document {
  id: string;
  name: string;
  type: 'sgk' | 'medical' | 'invoice' | 'other';
  uploadDate: string;
  size: string;
  status: 'processing' | 'completed' | 'error';
  url?: string;
}

interface PatientDocumentsTabProps {
  patientId: string;
}

export const PatientDocumentsTab: React.FC<PatientDocumentsTabProps> = ({ patientId }) => {
  const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedDocumentType, setSelectedDocumentType] = useState<string>('all');
  const [documents, setDocuments] = useState<Document[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [uploadProgress, setUploadProgress] = useState<{[key: string]: number}>({});
  const [dragActive, setDragActive] = useState(false);
  const [bulkUploadMode, setBulkUploadMode] = useState(false);
  const [documentNotes, setDocumentNotes] = useState('');
  
  // Toast helpers
  const { success, error, info } = useToastHelpers();


  // API functions
  const api = getXEarCRMAPIAutoGenerated();
  const { sgkGetPatientSgkDocuments, sgkUploadSgkDocument, sgkDeleteSgkDocument, sgkProcessOcr, automationTriggerSgkProcessing } = api;

  useEffect(() => {
    loadDocuments();
  }, [patientId]);

  const loadDocuments = async () => {
    try {
      setIsLoading(true);
      // Load SGK documents for the patient
      await sgkGetPatientSgkDocuments(patientId);
      
      // Mock data for now - replace with actual API response
      const mockDocuments: Document[] = [
        {
          id: '1',
          name: 'SGK Raporu - Ocak 2024.pdf',
          type: 'sgk',
          uploadDate: '2024-01-15',
          size: '2.3 MB',
          status: 'completed'
        },
        {
          id: '2',
          name: 'Odyoloji Testi Sonuçları.pdf',
          type: 'medical',
          uploadDate: '2024-01-10',
          size: '1.8 MB',
          status: 'completed'
        },
        {
          id: '3',
          name: 'Fatura - INV-2024-001.pdf',
          type: 'invoice',
          uploadDate: '2024-01-08',
          size: '0.5 MB',
          status: 'processing'
        }
      ];
      
      setDocuments(mockDocuments);
    } catch (loadError) {
      console.error('Error loading documents:', loadError);
      error('Dokümanlar yüklenirken bir hata oluştu.');
    } finally {
      setIsLoading(false);
    }
  };

  const filteredDocuments = documents.filter(doc => {
    const matchesSearch = doc.name.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = selectedDocumentType === 'all' || doc.type === selectedDocumentType;
    return matchesSearch && matchesType;
  });

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;
    
    await processFileUploads(Array.from(files));
  };

  const handleDragEnter = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    const files = Array.from(e.dataTransfer.files);
    if (bulkUploadMode) {
      setSelectedFiles(prev => [...prev, ...files]);
    } else {
      processFileUploads(files);
    }
  };

  const processFileUploads = async (files: File[]) => {
    try {
      setIsUploading(true);
      
      for (const file of files) {
        const fileId = `${file.name}_${Date.now()}`;
        setUploadProgress(prev => ({ ...prev, [fileId]: 0 }));
        
        // Create FormData for file upload
        const formData = new FormData();
        formData.append('file', file);
        formData.append('patient_id', patientId);
        formData.append('document_type', selectedDocumentType === 'all' ? 'other' : selectedDocumentType);
        formData.append('notes', documentNotes);
        
        // Simulate upload progress
        const progressInterval = setInterval(() => {
          setUploadProgress(prev => {
            const currentProgress = prev[fileId] || 0;
            if (currentProgress >= 90) {
              clearInterval(progressInterval);
              return prev;
            }
            return { ...prev, [fileId]: currentProgress + 10 };
          });
        }, 200);
        
        // Upload document based on type
        if (selectedDocumentType === 'sgk' || file.name.toLowerCase().includes('sgk')) {
          await sgkUploadSgkDocument(formData as any);
          
          // Trigger OCR processing for SGK documents
          await sgkProcessOcr({
            document_id: `temp_${Date.now()}`,
            patient_id: patientId
          });
          
          // Trigger automated SGK processing
          await automationTriggerSgkProcessing({
            patient_id: patientId,
            document_id: `temp_${Date.now()}`
          });
        }
        
        // Complete progress
        clearInterval(progressInterval);
        setUploadProgress(prev => ({ ...prev, [fileId]: 100 }));
        
        // Remove progress after delay
        setTimeout(() => {
          setUploadProgress(prev => {
            const newProgress = { ...prev };
            delete newProgress[fileId];
            return newProgress;
          });
        }, 2000);
      }
      
      success(`${files.length} doküman başarıyla yüklendi.`);
      
      // Reload documents and reset form
      await loadDocuments();
      setIsUploadModalOpen(false);
      setSelectedFiles([]);
      setDocumentNotes('');
    } catch (err) {
      console.error('Error uploading files:', err);
      error('Doküman yüklenirken bir hata oluştu.');
    } finally {
      setIsUploading(false);
    }
  };

  const removeSelectedFile = (index: number) => {
    setSelectedFiles(prev => prev.filter((_, i) => i !== index));
  };

  const processBulkUpload = async () => {
    if (selectedFiles.length === 0) return;
    await processFileUploads(selectedFiles);
  };

  const handleViewDocument = (documentId: string) => {
    const document = documents.find(doc => doc.id === documentId);
    if (document?.url) {
      window.open(document.url, '_blank');
    } else {
      info('Doküman görüntüleme özelliği yakında eklenecek.');
    }
  };

  const handleDownloadDocument = (documentId: string) => {
    const document = documents.find(doc => doc.id === documentId);
    if (document) {
      // Create a temporary download link
      const link = window.document.createElement('a');
      link.href = document.url || '#';
      link.download = document.name;
      window.document.body.appendChild(link);
      link.click();
      window.document.body.removeChild(link);
    }
  };

  const handleDeleteDocument = async (documentId: string) => {
    try {
      await sgkDeleteSgkDocument(documentId);
      
      success('Doküman başarıyla silindi.');
      
      // Reload documents
      await loadDocuments();
    } catch (err) {
      console.error('Error deleting document:', err);
      error('Doküman silinirken bir hata oluştu.');
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      case 'processing':
        return <Clock className="w-4 h-4 text-yellow-500" />;
      case 'error':
        return <AlertCircle className="w-4 h-4 text-red-500" />;
      default:
        return <Clock className="w-4 h-4 text-gray-500" />;
    }
  };

  const getStatusBadge = (status: string) => {
    const variants = {
      completed: 'bg-green-100 text-green-800',
      processing: 'bg-yellow-100 text-yellow-800',
      error: 'bg-red-100 text-red-800'
    };
    
    const labels = {
      completed: 'Tamamlandı',
      processing: 'İşleniyor',
      error: 'Hata'
    };

    return (
      <Badge className={variants[status as keyof typeof variants] || 'bg-gray-100 text-gray-800'}>
        {labels[status as keyof typeof labels] || status}
      </Badge>
    );
  };

  const formatFileSize = (sizeStr: string) => {
    return sizeStr; // Already formatted in mock data
  };

  return (
    <div className="space-y-6">
      {/* Upload Modal */}
      {isUploadModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-medium">
                {bulkUploadMode ? 'Toplu Belge Yükleme' : 'Belge Yükle'}
              </h3>
              <div className="flex items-center space-x-2">
                <Button
                  onClick={() => setBulkUploadMode(!bulkUploadMode)}
                  variant="outline"
                  size="sm"
                >
                  {bulkUploadMode ? 'Tekli Mod' : 'Toplu Mod'}
                </Button>
                <Button
                  onClick={() => setIsUploadModalOpen(false)}
                  variant="ghost"
                  size="sm"
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <div className="space-y-4">
              {/* Drag and Drop Area */}
              <div
                className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
                  dragActive 
                    ? 'border-blue-500 bg-blue-50' 
                    : 'border-gray-300 hover:border-gray-400'
                }`}
                onDragEnter={handleDragEnter}
                onDragLeave={handleDragLeave}
                onDragOver={handleDragOver}
                onDrop={handleDrop}
              >
                <Upload className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                <p className="text-lg font-medium text-gray-900 mb-2">
                  Dosyaları buraya sürükleyin veya seçin
                </p>
                <p className="text-sm text-gray-500 mb-4">
                  PDF, JPG, PNG, DOC, DOCX formatları desteklenir
                </p>
                <input
                  type="file"
                  accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
                  onChange={handleFileUpload}
                  multiple={bulkUploadMode}
                  className="hidden"
                  id="file-upload"
                  disabled={isUploading}
                />
                <Button
                  onClick={() => document.getElementById('file-upload')?.click()}
                  disabled={isUploading}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  Dosya Seç
                </Button>
              </div>

              {/* Selected Files (Bulk Mode) */}
              {bulkUploadMode && selectedFiles.length > 0 && (
                <div className="space-y-2">
                  <h4 className="font-medium text-gray-900">
                    Seçilen Dosyalar ({selectedFiles.length})
                  </h4>
                  <div className="max-h-40 overflow-y-auto space-y-2">
                    {selectedFiles.map((file, index) => (
                      <div key={index} className="flex items-center justify-between p-2 bg-gray-50 rounded">
                        <div className="flex items-center space-x-2">
                          <FileText className="w-4 h-4 text-gray-500" />
                          <span className="text-sm">{file.name}</span>
                          <span className="text-xs text-gray-500">
                            ({(file.size / 1024 / 1024).toFixed(2)} MB)
                          </span>
                        </div>
                        <Button
                          onClick={() => removeSelectedFile(index)}
                          variant="ghost"
                          size="sm"
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Upload Progress */}
              {Object.keys(uploadProgress).length > 0 && (
                <div className="space-y-2">
                  <h4 className="font-medium text-gray-900">Yükleme Durumu</h4>
                  {Object.entries(uploadProgress).map(([fileId, progress]) => (
                    <div key={fileId} className="space-y-1">
                      <div className="flex justify-between text-sm">
                        <span>{fileId.split('_')[0]}</span>
                        <span>{progress}%</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                          style={{ width: `${progress}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Document Type and Notes */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Belge Türü
                  </label>
                  <Select
                    value={selectedDocumentType}
                    onChange={(e) => setSelectedDocumentType(e.target.value)}
                    options={[
                      { value: 'other', label: 'Diğer' },
                      { value: 'sgk', label: 'SGK Belgesi' },
                      { value: 'medical', label: 'Tıbbi Rapor' },
                      { value: 'invoice', label: 'Fatura' }
                    ]}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Notlar (Opsiyonel)
                  </label>
                  <Input
                    value={documentNotes}
                    onChange={(e) => setDocumentNotes(e.target.value)}
                    placeholder="Belge hakkında notlar..."
                  />
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex justify-end space-x-3">
                <Button
                  onClick={() => {
                    setIsUploadModalOpen(false);
                    setSelectedFiles([]);
                    setDocumentNotes('');
                  }}
                  variant="outline"
                  disabled={isUploading}
                >
                  İptal
                </Button>
                {bulkUploadMode && selectedFiles.length > 0 && (
                  <Button 
                    onClick={processBulkUpload}
                    disabled={isUploading}
                    className="bg-green-600 hover:bg-green-700"
                  >
                    {isUploading ? 'Yükleniyor...' : `${selectedFiles.length} Dosyayı Yükle`}
                  </Button>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Header with Upload Button */}
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-medium text-gray-900">Belge Yönetimi</h3>
        <Button
          onClick={() => setIsUploadModalOpen(true)}
          className="bg-blue-600 hover:bg-blue-700"
        >
          <Upload className="w-4 h-4 mr-2" />
          Belge Yükle
        </Button>
      </div>

      {/* Search and Filter */}
      <div className="flex space-x-4">
        <div className="relative flex-1">
          <Search className="w-4 h-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
          <Input
            placeholder="Belge ara..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        <Select
          value={selectedDocumentType}
          onChange={(e) => setSelectedDocumentType(e.target.value)}
          options={[
            { value: 'all', label: 'Tümü' },
            { value: 'sgk', label: 'SGK' },
            { value: 'medical', label: 'Tıbbi' },
            { value: 'invoice', label: 'Fatura' },
            { value: 'other', label: 'Diğer' }
          ]}
        />
      </div>

      {/* Documents Grid */}
      {isLoading ? (
        <div className="text-center py-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-2 text-gray-500">Dokümanlar yükleniyor...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredDocuments.map((doc) => (
            <Card key={doc.id} className="hover:shadow-md transition-shadow">
              <CardContent className="p-4">
                <div className="flex items-start space-x-3 mb-3">
                  <FileText className="w-8 h-8 text-blue-600 flex-shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-gray-900 truncate">{doc.name}</p>
                    <p className="text-sm text-gray-500 capitalize">{doc.type}</p>
                    <p className="text-xs text-gray-400">
                      {formatFileSize(doc.size)} • {new Date(doc.uploadDate).toLocaleDateString('tr-TR')}
                    </p>
                  </div>
                  <div className="flex items-center space-x-2">
                    {getStatusIcon(doc.status)}
                    {getStatusBadge(doc.status)}
                  </div>
                </div>
                <div className="flex justify-end space-x-2">
                  <Button
                    onClick={() => handleViewDocument(doc.id)}
                    variant="outline"
                    size="sm"
                  >
                    <Eye className="w-4 h-4" />
                  </Button>
                  <Button
                    onClick={() => handleDownloadDocument(doc.id)}
                    variant="outline"
                    size="sm"
                  >
                    <Download className="w-4 h-4" />
                  </Button>
                  <Button
                    onClick={() => handleDeleteDocument(doc.id)}
                    variant="outline"
                    size="sm"
                    className="text-red-600 hover:text-red-800"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
          {filteredDocuments.length === 0 && (
            <div className="col-span-full text-center py-8 text-gray-500">
              <FileText className="w-12 h-12 mx-auto mb-4 text-gray-300" />
              <p>
                {searchTerm || selectedDocumentType !== 'all' 
                  ? 'Arama kriterlerine uygun belge bulunamadı.' 
                  : 'Henüz yüklenmiş belge bulunmamaktadır.'
                }
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};