import {
  sgkUploadSgkDocument,
  sgkDeleteSgkDocument,
  sgkProcessOcr,
  automationTriggerSgkProcessing,
  sgkGetPatientSgkDocuments
} from '../../api/generated/xEarCRMAPIAutoGenerated';
import { sgkService as fullSgkService } from '../sgk.service';

// SGK Service - handles SGK document operations
export const sgkService = {
  // Upload SGK document
  uploadDocument: (body?: any) => sgkUploadSgkDocument(body),

  // Delete SGK document
  deleteDocument: (documentId: string) => sgkDeleteSgkDocument(documentId),

  // List SGK documents for a patient
  listDocuments: (patientId: string) => sgkGetPatientSgkDocuments(patientId),

  // Process OCR
  processOcr: (body?: any) => sgkProcessOcr(body),

  // Trigger SGK processing
  triggerProcessing: (body?: any) => automationTriggerSgkProcessing(body),

  // Workflow methods from the full SGK service
  getWorkflow: (workflowId: string) => fullSgkService.getWorkflow(workflowId),
  updateWorkflowStatus: (workflowId: string, status: any, notes?: string) => fullSgkService.updateWorkflowStatus(workflowId, status, notes),
  createWorkflow: (patientId: string, documentId?: string, workflowType?: string) => fullSgkService.createWorkflow(patientId, documentId, workflowType),

  // Document management methods from the full SGK service
  validateDocument: (data: any) => fullSgkService.validateDocument(data),
  createDocument: (data: any) => fullSgkService.createDocument(data),
  processDocument: (request: any) => fullSgkService.processDocument(request),
  updateDocumentStatus: (id: string, status: any) => fullSgkService.updateDocument(id, { processingStatus: status }),
};

export default sgkService;
