import { getXEarCRMAPIAutoGenerated } from '../../api/generated/xEarCRMAPIAutoGenerated';

const api = getXEarCRMAPIAutoGenerated();
const { sgkUploadSgkDocument, sgkDeleteSgkDocument, sgkProcessOcr, automationTriggerSgkProcessing } = api;

// SGK Service - handles SGK document operations
export const sgkService = {
  // Upload SGK document
  uploadDocument: (body?: any, opts?: any) => sgkUploadSgkDocument(body, opts),
  
  // Delete SGK document
  deleteDocument: (documentId: string, opts?: any) => sgkDeleteSgkDocument(documentId, opts),
  
  // List SGK documents for a patient - using direct axios call since no specific endpoint exists
  listDocuments: async (patientId: string, opts?: any) => {
    const axios = (await import('axios')).default;
    return axios.get(`/api/patients/${patientId}/sgk-documents`, opts);
  },
  
  // Process OCR
  processOcr: (body?: any, opts?: any) => sgkProcessOcr(body, opts),
  
  // Trigger SGK processing
  triggerProcessing: (body?: any, opts?: any) => automationTriggerSgkProcessing(body, opts),
};

export default sgkService;
