/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear Admin API
 * API for X-Ear Admin Panel
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminGetFeatures200,
  AdminUpdateFeatures200,
  AdminUpdateFeaturesBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * @summary Get system feature flags
 */
export const adminGetFeatures = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<AdminGetFeatures200>(
      {url: `/admin/features`, method: 'GET', signal
    },
      );
    }
  



export const getAdminGetFeaturesQueryKey = () => {
    return [
    `/admin/features`
    ] as const;
    }

    
export const getAdminGetFeaturesQueryOptions = <TData = Awaited<ReturnType<typeof adminGetFeatures>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetFeaturesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetFeatures>>> = ({ signal }) => adminGetFeatures(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AdminGetFeaturesQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetFeatures>>>
export type AdminGetFeaturesQueryError = unknown


export function useAdminGetFeatures<TData = Awaited<ReturnType<typeof adminGetFeatures>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetFeatures>>,
          TError,
          Awaited<ReturnType<typeof adminGetFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetFeatures<TData = Awaited<ReturnType<typeof adminGetFeatures>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetFeatures>>,
          TError,
          Awaited<ReturnType<typeof adminGetFeatures>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetFeatures<TData = Awaited<ReturnType<typeof adminGetFeatures>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get system feature flags
 */

export function useAdminGetFeatures<TData = Awaited<ReturnType<typeof adminGetFeatures>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetFeatures>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAdminGetFeaturesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update system feature flags
 */
export const adminUpdateFeatures = (
    adminUpdateFeaturesBody: AdminUpdateFeaturesBody,
 ) => {
      
      
      return adminApi<AdminUpdateFeatures200>(
      {url: `/admin/features`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: adminUpdateFeaturesBody
    },
      );
    }
  


export const getAdminUpdateFeaturesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFeatures>>, TError,{data: AdminUpdateFeaturesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFeatures>>, TError,{data: AdminUpdateFeaturesBody}, TContext> => {

const mutationKey = ['adminUpdateFeatures'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateFeatures>>, {data: AdminUpdateFeaturesBody}> = (props) => {
          const {data} = props ?? {};

          return  adminUpdateFeatures(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateFeaturesMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateFeatures>>>
    export type AdminUpdateFeaturesMutationBody = AdminUpdateFeaturesBody
    export type AdminUpdateFeaturesMutationError = unknown

    /**
 * @summary Update system feature flags
 */
export const useAdminUpdateFeatures = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateFeatures>>, TError,{data: AdminUpdateFeaturesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateFeatures>>,
        TError,
        {data: AdminUpdateFeaturesBody},
        TContext
      > => {

      const mutationOptions = getAdminUpdateFeaturesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    