/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import type { BranchUpdateName } from './branchUpdateName';
import type { BranchUpdateAddress } from './branchUpdateAddress';
import type { BranchUpdatePhone } from './branchUpdatePhone';
import type { BranchUpdateEmail } from './branchUpdateEmail';

export interface BranchUpdate {
  name?: BranchUpdateName;
  address?: BranchUpdateAddress;
  phone?: BranchUpdatePhone;
  email?: BranchUpdateEmail;
}
