/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */

export type CampaignType = typeof CampaignType[keyof typeof CampaignType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignType = {
  sms: 'sms',
  email: 'email',
  notification: 'notification',
} as const;
