/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OcrExtractEntitiesBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Create new entities
 * @summary Extract entities from image using OCR
 */
export const ocrExtractEntities = (
    ocrExtractEntitiesBody?: OcrExtractEntitiesBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/entities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ocrExtractEntitiesBody, signal
    },
      );
    }
  


export const getOcrExtractEntitiesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrExtractEntities>>, TError,{data: OcrExtractEntitiesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ocrExtractEntities>>, TError,{data: OcrExtractEntitiesBody}, TContext> => {

const mutationKey = ['ocrExtractEntities'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ocrExtractEntities>>, {data: OcrExtractEntitiesBody}> = (props) => {
          const {data} = props ?? {};

          return  ocrExtractEntities(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OcrExtractEntitiesMutationResult = NonNullable<Awaited<ReturnType<typeof ocrExtractEntities>>>
    export type OcrExtractEntitiesMutationBody = OcrExtractEntitiesBody
    export type OcrExtractEntitiesMutationError = unknown

    /**
 * @summary Extract entities from image using OCR
 */
export const useOcrExtractEntities = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrExtractEntities>>, TError,{data: OcrExtractEntitiesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ocrExtractEntities>>,
        TError,
        {data: OcrExtractEntitiesBody},
        TContext
      > => {

      const mutationOptions = getOcrExtractEntitiesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    