/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAutomationLogsParams,
  HTTPValidationError
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * Get automation system status
 * @summary Get Automation Status
 */
export const getAutomationStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/automation/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetAutomationStatusQueryKey = () => {
    return [
    `/api/automation/status`
    ] as const;
    }

    
export const getGetAutomationStatusQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationStatus>>> = ({ signal }) => getAutomationStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAutomationStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationStatus>>>
export type GetAutomationStatusQueryError = unknown


export function useGetAutomationStatus<TData = Awaited<ReturnType<typeof getAutomationStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStatus>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAutomationStatus<TData = Awaited<ReturnType<typeof getAutomationStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationStatus>>,
          TError,
          Awaited<ReturnType<typeof getAutomationStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAutomationStatus<TData = Awaited<ReturnType<typeof getAutomationStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Automation Status
 */

export function useGetAutomationStatus<TData = Awaited<ReturnType<typeof getAutomationStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAutomationStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Trigger SGK document processing
 * @summary Trigger Sgk Processing
 */
export const triggerSgkProcessing = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/automation/sgk/process`, method: 'POST', signal
    },
      );
    }
  


export const getTriggerSgkProcessingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerSgkProcessing>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof triggerSgkProcessing>>, TError,void, TContext> => {

const mutationKey = ['triggerSgkProcessing'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerSgkProcessing>>, void> = () => {
          

          return  triggerSgkProcessing()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TriggerSgkProcessingMutationResult = NonNullable<Awaited<ReturnType<typeof triggerSgkProcessing>>>
    
    export type TriggerSgkProcessingMutationError = unknown

    /**
 * @summary Trigger Sgk Processing
 */
export const useTriggerSgkProcessing = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerSgkProcessing>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerSgkProcessing>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTriggerSgkProcessingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Trigger system backup
 * @summary Trigger Backup
 */
export const triggerBackup = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/automation/backup`, method: 'POST', signal
    },
      );
    }
  


export const getTriggerBackupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerBackup>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof triggerBackup>>, TError,void, TContext> => {

const mutationKey = ['triggerBackup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerBackup>>, void> = () => {
          

          return  triggerBackup()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TriggerBackupMutationResult = NonNullable<Awaited<ReturnType<typeof triggerBackup>>>
    
    export type TriggerBackupMutationError = unknown

    /**
 * @summary Trigger Backup
 */
export const useTriggerBackup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerBackup>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerBackup>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTriggerBackupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get automation logs
 * @summary Get Automation Logs
 */
export const getAutomationLogs = (
    params?: GetAutomationLogsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/automation/logs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAutomationLogsQueryKey = (params?: GetAutomationLogsParams,) => {
    return [
    `/api/automation/logs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAutomationLogsQueryOptions = <TData = Awaited<ReturnType<typeof getAutomationLogs>>, TError = HTTPValidationError>(params?: GetAutomationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutomationLogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutomationLogs>>> = ({ signal }) => getAutomationLogs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAutomationLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getAutomationLogs>>>
export type GetAutomationLogsQueryError = HTTPValidationError


export function useGetAutomationLogs<TData = Awaited<ReturnType<typeof getAutomationLogs>>, TError = HTTPValidationError>(
 params: undefined |  GetAutomationLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationLogs>>,
          TError,
          Awaited<ReturnType<typeof getAutomationLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAutomationLogs<TData = Awaited<ReturnType<typeof getAutomationLogs>>, TError = HTTPValidationError>(
 params?: GetAutomationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutomationLogs>>,
          TError,
          Awaited<ReturnType<typeof getAutomationLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAutomationLogs<TData = Awaited<ReturnType<typeof getAutomationLogs>>, TError = HTTPValidationError>(
 params?: GetAutomationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Automation Logs
 */

export function useGetAutomationLogs<TData = Awaited<ReturnType<typeof getAutomationLogs>>, TError = HTTPValidationError>(
 params?: GetAutomationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutomationLogs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAutomationLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




