/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear Admin API
 * API for X-Ear Admin Panel
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminGetActivityLogDetail200,
  AdminGetActivityLogFilterOptions200,
  AdminGetActivityLogs200,
  AdminGetActivityLogsParams,
  AdminGetActivityLogsStats200,
  AdminGetActivityLogsStatsParams
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Returns activity logs across all tenants. Only accessible by platform admins.
 * @summary Get Activity Logs (Platform Admin - all tenants)
 */
export const adminGetActivityLogs = (
    params?: AdminGetActivityLogsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<AdminGetActivityLogs200>(
      {url: `/api/admin/activity-logs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminGetActivityLogsQueryKey = (params?: AdminGetActivityLogsParams,) => {
    return [
    `/api/admin/activity-logs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminGetActivityLogsQueryOptions = <TData = Awaited<ReturnType<typeof adminGetActivityLogs>>, TError = void>(params?: AdminGetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetActivityLogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetActivityLogs>>> = ({ signal }) => adminGetActivityLogs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AdminGetActivityLogsQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetActivityLogs>>>
export type AdminGetActivityLogsQueryError = void


export function useAdminGetActivityLogs<TData = Awaited<ReturnType<typeof adminGetActivityLogs>>, TError = void>(
 params: undefined |  AdminGetActivityLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogs>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogs<TData = Awaited<ReturnType<typeof adminGetActivityLogs>>, TError = void>(
 params?: AdminGetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogs>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogs<TData = Awaited<ReturnType<typeof adminGetActivityLogs>>, TError = void>(
 params?: AdminGetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Activity Logs (Platform Admin - all tenants)
 */

export function useAdminGetActivityLogs<TData = Awaited<ReturnType<typeof adminGetActivityLogs>>, TError = void>(
 params?: AdminGetActivityLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAdminGetActivityLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns statistics about activity logs across all tenants
 * @summary Get Activity Logs Statistics
 */
export const adminGetActivityLogsStats = (
    params?: AdminGetActivityLogsStatsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<AdminGetActivityLogsStats200>(
      {url: `/api/admin/activity-logs/stats`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAdminGetActivityLogsStatsQueryKey = (params?: AdminGetActivityLogsStatsParams,) => {
    return [
    `/api/admin/activity-logs/stats`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminGetActivityLogsStatsQueryOptions = <TData = Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError = unknown>(params?: AdminGetActivityLogsStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetActivityLogsStatsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetActivityLogsStats>>> = ({ signal }) => adminGetActivityLogsStats(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AdminGetActivityLogsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetActivityLogsStats>>>
export type AdminGetActivityLogsStatsQueryError = unknown


export function useAdminGetActivityLogsStats<TData = Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError = unknown>(
 params: undefined |  AdminGetActivityLogsStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogsStats>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogsStats<TData = Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError = unknown>(
 params?: AdminGetActivityLogsStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogsStats>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogsStats<TData = Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError = unknown>(
 params?: AdminGetActivityLogsStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Activity Logs Statistics
 */

export function useAdminGetActivityLogsStats<TData = Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError = unknown>(
 params?: AdminGetActivityLogsStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAdminGetActivityLogsStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns available filter options for activity logs
 * @summary Get Activity Log Filter Options
 */
export const adminGetActivityLogFilterOptions = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<AdminGetActivityLogFilterOptions200>(
      {url: `/api/admin/activity-logs/filter-options`, method: 'GET', signal
    },
      );
    }
  



export const getAdminGetActivityLogFilterOptionsQueryKey = () => {
    return [
    `/api/admin/activity-logs/filter-options`
    ] as const;
    }

    
export const getAdminGetActivityLogFilterOptionsQueryOptions = <TData = Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetActivityLogFilterOptionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>> = ({ signal }) => adminGetActivityLogFilterOptions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AdminGetActivityLogFilterOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>>
export type AdminGetActivityLogFilterOptionsQueryError = unknown


export function useAdminGetActivityLogFilterOptions<TData = Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogFilterOptions<TData = Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogFilterOptions<TData = Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Activity Log Filter Options
 */

export function useAdminGetActivityLogFilterOptions<TData = Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogFilterOptions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAdminGetActivityLogFilterOptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a single activity log with full details
 * @summary Get Activity Log Detail
 */
export const adminGetActivityLogDetail = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return adminApi<AdminGetActivityLogDetail200>(
      {url: `/api/admin/activity-logs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getAdminGetActivityLogDetailQueryKey = (id?: string,) => {
    return [
    `/api/admin/activity-logs/${id}`
    ] as const;
    }

    
export const getAdminGetActivityLogDetailQueryOptions = <TData = Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetActivityLogDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetActivityLogDetail>>> = ({ signal }) => adminGetActivityLogDetail(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AdminGetActivityLogDetailQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetActivityLogDetail>>>
export type AdminGetActivityLogDetailQueryError = void


export function useAdminGetActivityLogDetail<TData = Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogDetail>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogDetail<TData = Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetActivityLogDetail>>,
          TError,
          Awaited<ReturnType<typeof adminGetActivityLogDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAdminGetActivityLogDetail<TData = Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Activity Log Detail
 */

export function useAdminGetActivityLogDetail<TData = Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetActivityLogDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAdminGetActivityLogDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




