/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtsRouteImport } from './routes/uts'
import { Route as TestRouteImport } from './routes/test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as SgkIndexRouteImport } from './routes/sgk/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers/$supplierId'
import { Route as SgkDownloadsRouteImport } from './routes/sgk/downloads'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsIntegrationRouteImport } from './routes/settings/integration'
import { Route as SettingsCompanyRouteImport } from './routes/settings/company'
import { Route as ReportsActivityRouteImport } from './routes/reports/activity'
import { Route as PosSuccessRouteImport } from './routes/pos/success'
import { Route as PosFailRouteImport } from './routes/pos/fail'
import { Route as PartiesPartyIdRouteImport } from './routes/parties/$partyId'
import { Route as InvoicesPurchasesRouteImport } from './routes/invoices/purchases'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as InventoryIdRouteImport } from './routes/inventory/$id'

const UtsRoute = UtsRouteImport.update({
  id: '/uts',
  path: '/uts',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SgkIndexRoute = SgkIndexRouteImport.update({
  id: '/sgk/',
  path: '/sgk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const SgkDownloadsRoute = SgkDownloadsRouteImport.update({
  id: '/sgk/downloads',
  path: '/sgk/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationRoute = SettingsIntegrationRouteImport.update({
  id: '/settings/integration',
  path: '/settings/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsActivityRoute = ReportsActivityRouteImport.update({
  id: '/reports/activity',
  path: '/reports/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSuccessRoute = PosSuccessRouteImport.update({
  id: '/pos/success',
  path: '/pos/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PosFailRoute = PosFailRouteImport.update({
  id: '/pos/fail',
  path: '/pos/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesPartyIdRoute = PartiesPartyIdRouteImport.update({
  id: '/parties/$partyId',
  path: '/parties/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPurchasesRoute = InvoicesPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/campaigns': typeof CampaignsRoute
  '/cashflow': typeof CashflowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/test': typeof TestRoute
  '/uts': typeof UtsRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/purchases': typeof InvoicesPurchasesRoute
  '/parties/$partyId': typeof PartiesPartyIdRoute
  '/pos/fail': typeof PosFailRoute
  '/pos/success': typeof PosSuccessRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integration': typeof SettingsIntegrationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/sgk/downloads': typeof SgkDownloadsRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sgk/': typeof SgkIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/campaigns': typeof CampaignsRoute
  '/cashflow': typeof CashflowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/test': typeof TestRoute
  '/uts': typeof UtsRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/purchases': typeof InvoicesPurchasesRoute
  '/parties/$partyId': typeof PartiesPartyIdRoute
  '/pos/fail': typeof PosFailRoute
  '/pos/success': typeof PosSuccessRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integration': typeof SettingsIntegrationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/sgk/downloads': typeof SgkDownloadsRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/parties': typeof PartiesIndexRoute
  '/pos': typeof PosIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sgk': typeof SgkIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/campaigns': typeof CampaignsRoute
  '/cashflow': typeof CashflowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/test': typeof TestRoute
  '/uts': typeof UtsRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/purchases': typeof InvoicesPurchasesRoute
  '/parties/$partyId': typeof PartiesPartyIdRoute
  '/pos/fail': typeof PosFailRoute
  '/pos/success': typeof PosSuccessRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integration': typeof SettingsIntegrationRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/sgk/downloads': typeof SgkDownloadsRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sgk/': typeof SgkIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/campaigns'
    | '/cashflow'
    | '/forgot-password'
    | '/inventory'
    | '/invoices'
    | '/profile'
    | '/test'
    | '/uts'
    | '/inventory/$id'
    | '/invoices/new'
    | '/invoices/purchases'
    | '/parties/$partyId'
    | '/pos/fail'
    | '/pos/success'
    | '/reports/activity'
    | '/settings/company'
    | '/settings/integration'
    | '/settings/roles'
    | '/settings/subscription'
    | '/settings/team'
    | '/sgk/downloads'
    | '/suppliers/$supplierId'
    | '/inventory/'
    | '/invoices/'
    | '/parties/'
    | '/pos/'
    | '/reports/'
    | '/sgk/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/campaigns'
    | '/cashflow'
    | '/forgot-password'
    | '/profile'
    | '/test'
    | '/uts'
    | '/inventory/$id'
    | '/invoices/new'
    | '/invoices/purchases'
    | '/parties/$partyId'
    | '/pos/fail'
    | '/pos/success'
    | '/reports/activity'
    | '/settings/company'
    | '/settings/integration'
    | '/settings/roles'
    | '/settings/subscription'
    | '/settings/team'
    | '/sgk/downloads'
    | '/suppliers/$supplierId'
    | '/inventory'
    | '/invoices'
    | '/parties'
    | '/pos'
    | '/reports'
    | '/sgk'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/campaigns'
    | '/cashflow'
    | '/forgot-password'
    | '/inventory'
    | '/invoices'
    | '/profile'
    | '/test'
    | '/uts'
    | '/inventory/$id'
    | '/invoices/new'
    | '/invoices/purchases'
    | '/parties/$partyId'
    | '/pos/fail'
    | '/pos/success'
    | '/reports/activity'
    | '/settings/company'
    | '/settings/integration'
    | '/settings/roles'
    | '/settings/subscription'
    | '/settings/team'
    | '/sgk/downloads'
    | '/suppliers/$supplierId'
    | '/inventory/'
    | '/invoices/'
    | '/parties/'
    | '/pos/'
    | '/reports/'
    | '/sgk/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CampaignsRoute: typeof CampaignsRoute
  CashflowRoute: typeof CashflowRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  TestRoute: typeof TestRoute
  UtsRoute: typeof UtsRoute
  PartiesPartyIdRoute: typeof PartiesPartyIdRoute
  PosFailRoute: typeof PosFailRoute
  PosSuccessRoute: typeof PosSuccessRoute
  ReportsActivityRoute: typeof ReportsActivityRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationRoute: typeof SettingsIntegrationRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SgkDownloadsRoute: typeof SgkDownloadsRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SgkIndexRoute: typeof SgkIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uts': {
      id: '/uts'
      path: '/uts'
      fullPath: '/uts'
      preLoaderRoute: typeof UtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgk/': {
      id: '/sgk/'
      path: '/sgk'
      fullPath: '/sgk/'
      preLoaderRoute: typeof SgkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgk/downloads': {
      id: '/sgk/downloads'
      path: '/sgk/downloads'
      fullPath: '/sgk/downloads'
      preLoaderRoute: typeof SgkDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integration': {
      id: '/settings/integration'
      path: '/settings/integration'
      fullPath: '/settings/integration'
      preLoaderRoute: typeof SettingsIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/activity': {
      id: '/reports/activity'
      path: '/reports/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof ReportsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/success': {
      id: '/pos/success'
      path: '/pos/success'
      fullPath: '/pos/success'
      preLoaderRoute: typeof PosSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/fail': {
      id: '/pos/fail'
      path: '/pos/fail'
      fullPath: '/pos/fail'
      preLoaderRoute: typeof PosFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$partyId': {
      id: '/parties/$partyId'
      path: '/parties/$partyId'
      fullPath: '/parties/$partyId'
      preLoaderRoute: typeof PartiesPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/purchases': {
      id: '/invoices/purchases'
      path: '/purchases'
      fullPath: '/invoices/purchases'
      preLoaderRoute: typeof InvoicesPurchasesRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryIdRoute: typeof InventoryIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryIdRoute: InventoryIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesPurchasesRoute: typeof InvoicesPurchasesRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesPurchasesRoute: InvoicesPurchasesRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  CampaignsRoute: CampaignsRoute,
  CashflowRoute: CashflowRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  TestRoute: TestRoute,
  UtsRoute: UtsRoute,
  PartiesPartyIdRoute: PartiesPartyIdRoute,
  PosFailRoute: PosFailRoute,
  PosSuccessRoute: PosSuccessRoute,
  ReportsActivityRoute: ReportsActivityRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationRoute: SettingsIntegrationRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SgkDownloadsRoute: SgkDownloadsRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  PosIndexRoute: PosIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SgkIndexRoute: SgkIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
