import { Input, Button, Textarea } from '@x-ear/ui-web';
import { useState, useEffect, useCallback } from 'react';
import { User, CheckCircle } from 'lucide-react';
import { partyService } from '../../services/party.service';
import { Party } from '../../types/party';
import citiesData from '../../data/cities.json';
import { SearchableSelect } from '../ui/SearchableSelect';

interface CustomerSectionCompactProps {
  isSGK?: boolean;
  customerId?: string;
  customerFirstName?: string;
  customerLastName?: string;
  customerTcNumber?: string;
  customerTaxNumber?: string;
  customerAddress?: string;
  customerCity?: string;
  customerDistrict?: string;
  onChange: (field: string, value: unknown) => void;
}

// SGK sabit bilgisi
const SGK_CUSTOMER = {
  id: '0',
  name: 'Sosyal Güvenlik Kurumu',
  taxNumber: '7750409379',
  address: 'Çankaya/ ANKARA - TÜRKİYE V.D ÇANKAYA VERGİ DAİRESİ (6257)'
};

export function CustomerSectionCompact({
  isSGK = false,
  customerId: _customerId,
  customerFirstName,
  customerLastName,
  customerTcNumber,
  customerTaxNumber,
  customerAddress,
  customerCity,
  customerDistrict,
  onChange
}: CustomerSectionCompactProps) {
  const [searchResults, setSearchResults] = useState<Party[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [_selectedParty, setSelectedParty] = useState<Party | null>(null);
  const [districts, setDistricts] = useState<string[]>([]);
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);

  // SGK modunda otomatik doldur
  useEffect(() => {
    if (isSGK) {
      onChange('customerId', SGK_CUSTOMER.id);
      onChange('customerFirstName', 'Sosyal Güvenlik');
      onChange('customerLastName', 'Kurumu');
      onChange('customerTaxNumber', SGK_CUSTOMER.taxNumber);
      onChange('customerAddress', SGK_CUSTOMER.address);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSGK]);

  // TC ile hasta arama
  const handleTcSearch = useCallback(async (tcNumber: string) => {
    if (tcNumber.length < 3) {
      setSearchResults([]);
      setShowResults(false);
      return;
    }

    console.log('TC ile arama yapılıyor:', tcNumber);
    setIsSearching(true);
    setShowResults(true);

    try {
      const result = await partyService.getParties({
        search: tcNumber,
        limit: 10
      });

      console.log('Arama sonucu:', result);

      if (result.parties && result.parties.length > 0) {
        setSearchResults(result.parties);
        console.log('Bulunan hasta sayısı:', result.parties.length);
      } else {
        setSearchResults([]);
        console.log('Hasta bulunamadı');
      }
    } catch (error) {
      console.error('Hasta arama hatası:', error);
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  }, []);

  // Ad ile hasta arama
  const handleNameSearch = useCallback(async (name: string) => {
    if (name.length < 2) {
      setSearchResults([]);
      setShowResults(false);
      return;
    }

    console.log('Ad ile arama yapılıyor:', name);
    setIsSearching(true);
    setShowResults(true);

    try {
      const result = await partyService.getParties({
        search: name,
        limit: 10
      });

      console.log('Arama sonucu:', result);

      if (result.parties && result.parties.length > 0) {
        setSearchResults(result.parties);
        console.log('Bulunan hasta sayısı:', result.parties.length);
      } else {
        setSearchResults([]);
        console.log('Hasta bulunamadı');
      }
    } catch (error) {
      console.error('Hasta arama hatası:', error);
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  }, []);

  // Hasta seçimi
  const handlePartySelect = useCallback((party: Party) => {
    setSelectedParty(party);
    setShowResults(false);
    setShowSuccessMessage(true);

    onChange('customerId', party.id);
    onChange('customerFirstName', party.firstName);
    onChange('customerLastName', party.lastName);
    onChange('customerTcNumber', party.tcNumber || '');
    onChange('customerTaxNumber', '');

    // Adres bilgilerini çek - Party tipindeki alan isimleri farklı olabilir
    // Öncelikle addressFull (generated types) kontrol et, sonra snake_case, sonra parçalı alanlardan oluştur
    let addressText = '';
    let cityValue = '';
    let districtValue = '';

    // Prefer full address fields generated by the API types
    addressText = (party.addressFull as string) || (party.address_full as string) || '';
    cityValue = (party.addressCity as string) || (party.address_city as string) || '';
    districtValue = (party.addressDistrict as string) || (party.address_district as string) || '';

    // Fallbacks: some records may have nested address object or separate street field
    interface LegacyPartyWithAddress extends Omit<Party, 'address'> {
      address?: string | { full?: string; street?: string; streetName?: string } | null;
    }
    const legacyParty = party as unknown as LegacyPartyWithAddress;

    if (!addressText && legacyParty.address) {
      const a = legacyParty.address;
      if (typeof a === 'string') addressText = a;
      else if (a && typeof a === 'object') addressText = a.full || a.street || a.streetName || '';
    }

    // If still empty, try composing from city/district
    if (!addressText) {
      const parts = [] as string[];
      if (districtValue) parts.push(districtValue);
      if (cityValue) parts.push(cityValue);
      addressText = parts.join(' - ');
    }

    onChange('customerAddress', addressText);
    onChange('customerCity', cityValue);
    onChange('customerDistrict', districtValue);

    // İl seçildiğinde ilçeleri yükle
    if (cityValue) {
      const cityData = citiesData.cities.find(c => c.name === cityValue);
      if (cityData) {
        setDistricts(cityData.districts);
      }
    }

    // Mesajı 3 saniye sonra gizle
    setTimeout(() => {
      setShowSuccessMessage(false);
    }, 3000);
  }, [onChange]);

  // İl değiştiğinde ilçeleri yükle
  const handleCityChange = useCallback((city: string) => {
    onChange('customerCity', city);
    onChange('customerDistrict', ''); // İlçeyi sıfırla

    const cityData = citiesData.cities.find(c => c.name === city);
    if (cityData) {
      setDistricts(cityData.districts);
    } else {
      setDistricts([]);
    }
  }, [onChange]);

  // İlk yüklemede mevcut il varsa ilçeleri yükle
  useEffect(() => {
    if (customerCity) {
      const cityData = citiesData.cities.find(c => c.name === customerCity);
      if (cityData) {
        setDistricts(cityData.districts);
      }
    }
  }, [customerCity]);

  // Manuel düzenleme
  const handleManualEdit = useCallback((field: string, value: string) => {
    onChange(field, value);
  }, [onChange]);

  // Alıcıyı temizle
  const handleClearCustomer = useCallback(() => {
    setSelectedParty(null);
    setShowSuccessMessage(false);
    onChange('customerId', '');
    onChange('customerFirstName', '');
    onChange('customerLastName', '');
    onChange('customerTcNumber', '');
    onChange('customerTaxNumber', '');
    onChange('customerAddress', '');
    onChange('customerCity', '');
    onChange('customerDistrict', '');
    setDistricts([]);
  }, [onChange]);

  // SGK modu
  if (isSGK) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="p-4 border-b border-gray-200 bg-blue-50">
          <div className="flex items-center gap-2">
            <User className="text-blue-600" size={16} />
            <h3 className="text-sm font-bold text-gray-900">Fatura Alıcı</h3>
          </div>
        </div>
        <div className="p-4">
          <div className="space-y-3">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Alıcı Adı
              </label>
              <div className="text-sm text-gray-900 font-medium">
                {SGK_CUSTOMER.name}
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Vergi No
              </label>
              <div className="text-sm text-gray-600">
                {SGK_CUSTOMER.taxNumber}
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Adres
              </label>
              <div className="text-xs text-gray-600 leading-relaxed">
                {SGK_CUSTOMER.address}
              </div>
            </div>
          </div>
          <p className="mt-3 text-xs text-blue-600 bg-blue-50 p-2 rounded">
            SGK faturası için alıcı bilgisi sabittir.
          </p>
        </div>
      </div>
    );
  }

  // Normal mod
  return (
    <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
      <div className="p-4 border-b border-gray-200 bg-gray-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <User className="text-gray-600" size={16} />
            <h3 className="text-sm font-bold text-gray-900">Fatura Alıcı</h3>
          </div>
          {(customerFirstName || customerLastName || customerTcNumber || customerTaxNumber) && (
            <Button
              type="button"
              onClick={handleClearCustomer}
              variant="default"
              className="text-xs px-2 py-1 bg-red-100 hover:bg-red-200 text-red-700"
            >
              Alıcıyı Sil
            </Button>
          )}
        </div>
      </div>
      <div className="p-4">
        <div className="space-y-3">
          {/* TC / Vergi No - En Üstte */}
          <div className="relative">
            <label className="block text-xs font-medium text-gray-700 mb-1">
              TC / Vergi No <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <Input
                type="text"
                value={customerTcNumber || customerTaxNumber || ''}
                onChange={(e) => {
                  const value = e.target.value;
                  if (value.length === 11 && /^\d+$/.test(value)) {
                    handleManualEdit('customerTcNumber', value);
                    handleManualEdit('customerTaxNumber', '');
                    handleTcSearch(value);
                  } else {
                    handleManualEdit('customerTaxNumber', value);
                    handleManualEdit('customerTcNumber', '');
                    setSearchResults([]);
                    setShowResults(false);
                  }
                }}
                placeholder="TC Kimlik (11 haneli) veya Vergi No"
                className="w-full text-sm"
              />
              {isSearching && (
                <div className="absolute right-2 top-2.5">
                  <div className="animate-spin h-4 w-4 border-2 border-blue-500 border-t-transparent rounded-full"></div>
                </div>
              )}
            </div>

            {/* TC Arama Sonuçları */}
            {showResults && searchResults.length > 0 && (
              <div className="absolute z-50 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-48 overflow-y-auto">
                {searchResults.map((party) => (
                  <Button
                    key={party.id}
                    type="button"
                    onClick={() => handlePartySelect(party)}
                    variant="ghost"
                    className="w-full px-3 py-2 text-left hover:bg-gray-50 border-b border-gray-100 last:border-b-0"
                  >
                    <div className="text-sm font-medium text-gray-900">
                      {party.firstName} {party.lastName}
                    </div>
                    {party.tcNumber && (
                      <div className="text-xs text-gray-500">TC: {party.tcNumber}</div>
                    )}
                    {party.phone && (
                      <div className="text-xs text-gray-500">Tel: {party.phone}</div>
                    )}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Ad ve Soyad - Yan Yana - Arama ile */}
          <div className="grid grid-cols-2 gap-2">
            <div className="relative">
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Ad <span className="text-red-500">*</span>
              </label>
              <Input
                type="text"
                value={customerFirstName || ''}
                onChange={(e) => {
                  const value = e.target.value;
                  handleManualEdit('customerFirstName', value);
                  // Ad girildiğinde arama yap
                  if (value.length >= 2) {
                    handleNameSearch(value);
                  }
                }}
                placeholder="Ad (hasta ara)"
                className="w-full text-sm"
              />
            </div>
            <div className="relative">
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Soyad <span className="text-red-500">*</span>
              </label>
              <Input
                type="text"
                value={customerLastName || ''}
                onChange={(e) => {
                  const value = e.target.value;
                  handleManualEdit('customerLastName', value);
                  // Soyad girildiğinde arama yap
                  if (value.length >= 2) {
                    handleNameSearch(value);
                  }
                }}
                placeholder="Soyad (hasta ara)"
                className="w-full text-sm"
              />
            </div>
          </div>

          {/* Ad/Soyad Arama Sonuçları */}
          {showResults && searchResults.length > 0 && !customerTcNumber && (
            <div className="relative">
              <div className="absolute z-50 w-full bg-white border border-gray-300 rounded-lg shadow-lg max-h-48 overflow-y-auto">
                {searchResults.map((party) => (
                  <Button
                    key={party.id}
                    type="button"
                    onClick={() => handlePartySelect(party)}
                    variant="ghost"
                    className="w-full px-3 py-2 text-left hover:bg-gray-50 border-b border-gray-100 last:border-b-0"
                  >
                    <div className="text-sm font-medium text-gray-900">
                      {party.firstName} {party.lastName}
                    </div>
                    {party.tcNumber && (
                      <div className="text-xs text-gray-500">TC: {party.tcNumber}</div>
                    )}
                    {party.phone && (
                      <div className="text-xs text-gray-500">Tel: {party.phone}</div>
                    )}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* İl ve İlçe - Yan Yana - Searchable */}
          <div className="grid grid-cols-2 gap-2">
            <div>
              <SearchableSelect
                label="İl"
                value={customerCity || ''}
                onChange={handleCityChange}
                options={citiesData.cities.map(city => ({
                  value: city.name,
                  label: city.name
                }))}
                placeholder="İl seçiniz..."
                fullWidth
              />
            </div>
            <div>
              <SearchableSelect
                label="İlçe"
                value={customerDistrict || ''}
                onChange={(value) => handleManualEdit('customerDistrict', value)}
                disabled={!customerCity || districts.length === 0}
                options={districts.map(district => ({
                  value: district,
                  label: district
                }))}
                placeholder="İlçe seçiniz..."
                fullWidth
              />
            </div>
          </div>

          {/* Adres */}
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">
              Adres
            </label>
            <Textarea
              value={customerAddress || ''}
              onChange={(e) => handleManualEdit('customerAddress', e.target.value)}
              placeholder="Fatura adresi"
              rows={2}
              className="w-full text-sm px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
            />
          </div>

          {showSuccessMessage && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-2 flex items-center gap-2 animate-fade-in">
              <CheckCircle className="text-green-600" size={14} />
              <p className="text-xs text-green-800">
                Hasta bulundu ve bilgiler dolduruldu
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
