/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear Admin API
 * API for X-Ear Admin Panel
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminDashboardMetrics200
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * @summary Get Dashboard Metrics
 */
export const getAdminDashboardMetrics = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<GetAdminDashboardMetrics200>(
      {url: `/admin/dashboard`, method: 'GET', signal
    },
      );
    }
  



export const getGetAdminDashboardMetricsQueryKey = () => {
    return [
    `/admin/dashboard`
    ] as const;
    }

    
export const getGetAdminDashboardMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminDashboardMetricsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminDashboardMetrics>>> = ({ signal }) => getAdminDashboardMetrics(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminDashboardMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminDashboardMetrics>>>
export type GetAdminDashboardMetricsQueryError = unknown


export function useGetAdminDashboardMetrics<TData = Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardMetrics>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardMetrics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminDashboardMetrics<TData = Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDashboardMetrics>>,
          TError,
          Awaited<ReturnType<typeof getAdminDashboardMetrics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminDashboardMetrics<TData = Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Dashboard Metrics
 */

export function useGetAdminDashboardMetrics<TData = Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDashboardMetrics>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminDashboardMetricsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




