/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkRegistration,
  HTTPValidationError,
  ListRegistrationsParams
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * List UTS device registrations
 * @summary List Registrations
 */
export const listRegistrations = (
    params?: ListRegistrationsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/uts/registrations`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListRegistrationsQueryKey = (params?: ListRegistrationsParams,) => {
    return [
    `/api/uts/registrations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRegistrationsQueryOptions = <TData = Awaited<ReturnType<typeof listRegistrations>>, TError = HTTPValidationError>(params?: ListRegistrationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRegistrationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRegistrations>>> = ({ signal }) => listRegistrations(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListRegistrationsQueryResult = NonNullable<Awaited<ReturnType<typeof listRegistrations>>>
export type ListRegistrationsQueryError = HTTPValidationError


export function useListRegistrations<TData = Awaited<ReturnType<typeof listRegistrations>>, TError = HTTPValidationError>(
 params: undefined |  ListRegistrationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRegistrations>>,
          TError,
          Awaited<ReturnType<typeof listRegistrations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListRegistrations<TData = Awaited<ReturnType<typeof listRegistrations>>, TError = HTTPValidationError>(
 params?: ListRegistrationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRegistrations>>,
          TError,
          Awaited<ReturnType<typeof listRegistrations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListRegistrations<TData = Awaited<ReturnType<typeof listRegistrations>>, TError = HTTPValidationError>(
 params?: ListRegistrationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Registrations
 */

export function useListRegistrations<TData = Awaited<ReturnType<typeof listRegistrations>>, TError = HTTPValidationError>(
 params?: ListRegistrationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrations>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListRegistrationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Start bulk UTS device registration job
 * @summary Start Bulk Registration
 */
export const startBulkRegistration = (
    bulkRegistration: BulkRegistration,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/uts/registrations/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkRegistration, signal
    },
      );
    }
  


export const getStartBulkRegistrationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startBulkRegistration>>, TError,{data: BulkRegistration}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startBulkRegistration>>, TError,{data: BulkRegistration}, TContext> => {

const mutationKey = ['startBulkRegistration'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startBulkRegistration>>, {data: BulkRegistration}> = (props) => {
          const {data} = props ?? {};

          return  startBulkRegistration(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartBulkRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof startBulkRegistration>>>
    export type StartBulkRegistrationMutationBody = BulkRegistration
    export type StartBulkRegistrationMutationError = HTTPValidationError

    /**
 * @summary Start Bulk Registration
 */
export const useStartBulkRegistration = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startBulkRegistration>>, TError,{data: BulkRegistration}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startBulkRegistration>>,
        TError,
        {data: BulkRegistration},
        TContext
      > => {

      const mutationOptions = getStartBulkRegistrationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get UTS registration job status
 * @summary Get Job Status
 */
export const getJobStatus = (
    jobId: string,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/uts/jobs/${jobId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetJobStatusQueryKey = (jobId?: string,) => {
    return [
    `/api/uts/jobs/${jobId}`
    ] as const;
    }

    
export const getGetJobStatusQueryOptions = <TData = Awaited<ReturnType<typeof getJobStatus>>, TError = HTTPValidationError>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobStatusQueryKey(jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobStatus>>> = ({ signal }) => getJobStatus(jobId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetJobStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getJobStatus>>>
export type GetJobStatusQueryError = HTTPValidationError


export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = HTTPValidationError>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobStatus>>,
          TError,
          Awaited<ReturnType<typeof getJobStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobStatus>>,
          TError,
          Awaited<ReturnType<typeof getJobStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Job Status
 */

export function useGetJobStatus<TData = Awaited<ReturnType<typeof getJobStatus>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetJobStatusQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Cancel UTS registration job
 * @summary Cancel Job
 */
export const cancelJob = (
    jobId: string,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/uts/jobs/${jobId}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getCancelJobMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelJob>>, TError,{jobId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelJob>>, TError,{jobId: string}, TContext> => {

const mutationKey = ['cancelJob'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelJob>>, {jobId: string}> = (props) => {
          const {jobId} = props ?? {};

          return  cancelJob(jobId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelJobMutationResult = NonNullable<Awaited<ReturnType<typeof cancelJob>>>
    
    export type CancelJobMutationError = HTTPValidationError

    /**
 * @summary Cancel Job
 */
export const useCancelJob = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelJob>>, TError,{jobId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelJob>>,
        TError,
        {jobId: string},
        TContext
      > => {

      const mutationOptions = getCancelJobMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    