/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  SuppliersAddProductSupplierBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Create new suppliers
 * @summary Add a supplier to a product
 */
export const suppliersAddProductSupplier = (
    productId: string,
    suppliersAddProductSupplierBody?: SuppliersAddProductSupplierBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/products/${productId}/suppliers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suppliersAddProductSupplierBody, signal
    },
      );
    }
  


export const getSuppliersAddProductSupplierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersAddProductSupplier>>, TError,{productId: string;data: SuppliersAddProductSupplierBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof suppliersAddProductSupplier>>, TError,{productId: string;data: SuppliersAddProductSupplierBody}, TContext> => {

const mutationKey = ['suppliersAddProductSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersAddProductSupplier>>, {productId: string;data: SuppliersAddProductSupplierBody}> = (props) => {
          const {productId,data} = props ?? {};

          return  suppliersAddProductSupplier(productId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SuppliersAddProductSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersAddProductSupplier>>>
    export type SuppliersAddProductSupplierMutationBody = SuppliersAddProductSupplierBody
    export type SuppliersAddProductSupplierMutationError = unknown

    /**
 * @summary Add a supplier to a product
 */
export const useSuppliersAddProductSupplier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersAddProductSupplier>>, TError,{productId: string;data: SuppliersAddProductSupplierBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersAddProductSupplier>>,
        TError,
        {productId: string;data: SuppliersAddProductSupplierBody},
        TContext
      > => {

      const mutationOptions = getSuppliersAddProductSupplierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    