"""
AI Layer Services

Business logic services:
- UsageTracker: Atomic usage counter updates
- QuotaHandler: Graceful quota exceeded handling
- KillSwitch: Global/tenant/capability kill switch management
- ApprovalGate: Approval workflow for high-risk actions
- GracefulDegradationService: System resilience when AI is unavailable
- AIFeatureFlagService: Feature flag integration for AI capabilities
- AuditService: Comprehensive audit logging with incident tagging and export
- DataRetentionService: Data deletion and retention policy management
"""

from ai.services.graceful_degradation import (
    GracefulDegradationService,
    AIAvailabilityStatus,
    AIAvailabilityState,
    DegradationReason,
    FallbackResponse,
    get_degradation_service,
    is_ai_available,
    is_ai_enabled,
    get_ai_availability_state,
    mark_ai_available,
    mark_ai_disabled,
    mark_ai_unavailable,
    record_ai_failure,
    record_ai_success,
    with_graceful_degradation,
    ensure_core_functionality,
)

from ai.services.feature_flags import (
    AIFeatureFlagService,
    AIFeatureFlag,
    FeatureFlagState,
    FeatureFlagDisabledError,
    get_feature_flag_service,
    is_feature_enabled,
    is_chat_enabled,
    is_actions_enabled,
    is_ocr_enabled,
    get_enabled_capabilities,
    disable_ai_for_tenant,
    enable_ai_for_tenant,
    require_feature_flag,
)

from ai.services.approval_gate import (
    ApprovalGate,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalResult,
    ApprovalQueueItem,
    get_approval_gate,
    reset_approval_gate,
    requires_approval,
)

from ai.services.usage_tracker import (
    UsageTracker,
    UsageRecord,
    UsageSummary,
    get_usage_tracker,
    reset_usage_tracker,
    track_usage,
    check_and_track_usage,
)

from ai.services.quota_handler import (
    QuotaHandler,
    QuotaInfo,
    QuotaStatus,
    QuotaExceededResponse,
    get_quota_handler,
    reset_quota_handler,
    require_quota,
    graceful_quota_check,
)

from ai.services.kill_switch import (
    KillSwitch,
    KillSwitchScope,
    KillSwitchState,
    KillSwitchCheckResult,
    KillSwitchActiveError,
    AICapability,
    get_kill_switch,
    reset_kill_switch,
    is_kill_switch_active,
    activate_global_kill_switch,
    deactivate_global_kill_switch,
    activate_tenant_kill_switch,
    deactivate_tenant_kill_switch,
    activate_capability_kill_switch,
    deactivate_capability_kill_switch,
    require_kill_switch_inactive,
)

from ai.services.audit_service import (
    AuditService,
    AuditContext,
    ModelContext,
    PolicyContext,
    AuditEntry,
    IncidentBundle,
    get_audit_service,
    REQUIRED_BASE_FIELDS,
    REQUIRED_REQUEST_FIELDS,
    REQUIRED_ACTION_FIELDS,
    REQUIRED_EXECUTION_FIELDS,
    REQUIRED_MODEL_FIELDS,
)

from ai.services.data_retention import (
    DataRetentionService,
    DeletionRequest,
    DeletionStatus,
    DeletionScope,
    RetentionPurgeResult,
    get_data_retention_service,
    reset_data_retention_service,
)

from ai.services.prompt_anonymizer import (
    PromptAnonymizer,
    AnonymizedPrompt,
    AnonymizedPromptStore,
    AnonymizationLevel,
    AnonymizationResult,
    get_prompt_anonymizer,
    get_anonymized_prompt_store,
    anonymize_prompt,
    reset_anonymizer_singletons,
)

from ai.services.metrics import (
    MetricsCollector,
    MetricType,
    MetricDataPoint,
    LatencyStats,
    RateStats,
    ApprovalStats,
    QuotaStats,
    SLAMetrics,
    get_metrics_collector,
    record_inference_latency,
    record_intent_latency,
    record_planning_latency,
    record_execution_latency,
    record_success,
    record_error,
    record_timeout,
    record_approval_granted,
    record_approval_rejected,
    record_auto_approved,
    record_quota_rejected,
    record_rate_limited,
    record_circuit_breaker_open,
    timed_operation,
    TimingContext,
)

from ai.services.alerting import (
    AlertingService,
    AlertSeverity,
    AlertType,
    AlertThresholds,
    Alert,
    get_alerting_service,
    check_and_alert,
    emit_circuit_breaker_alert,
)

__all__ = [
    # Graceful Degradation
    "GracefulDegradationService",
    "AIAvailabilityStatus",
    "AIAvailabilityState",
    "DegradationReason",
    "FallbackResponse",
    "get_degradation_service",
    "is_ai_available",
    "is_ai_enabled",
    "get_ai_availability_state",
    "mark_ai_available",
    "mark_ai_disabled",
    "mark_ai_unavailable",
    "record_ai_failure",
    "record_ai_success",
    "with_graceful_degradation",
    "ensure_core_functionality",
    # Feature Flags
    "AIFeatureFlagService",
    "AIFeatureFlag",
    "FeatureFlagState",
    "FeatureFlagDisabledError",
    "get_feature_flag_service",
    "is_feature_enabled",
    "is_chat_enabled",
    "is_actions_enabled",
    "is_ocr_enabled",
    "get_enabled_capabilities",
    "disable_ai_for_tenant",
    "enable_ai_for_tenant",
    "require_feature_flag",
    # Approval Gate
    "ApprovalGate",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalResult",
    "ApprovalQueueItem",
    "get_approval_gate",
    "reset_approval_gate",
    "requires_approval",
    # Usage Tracker
    "UsageTracker",
    "UsageRecord",
    "UsageSummary",
    "get_usage_tracker",
    "reset_usage_tracker",
    "track_usage",
    "check_and_track_usage",
    # Quota Handler
    "QuotaHandler",
    "QuotaInfo",
    "QuotaStatus",
    "QuotaExceededResponse",
    "get_quota_handler",
    "reset_quota_handler",
    "require_quota",
    "graceful_quota_check",
    # Kill Switch
    "KillSwitch",
    "KillSwitchScope",
    "KillSwitchState",
    "KillSwitchCheckResult",
    "KillSwitchActiveError",
    "AICapability",
    "get_kill_switch",
    "reset_kill_switch",
    "is_kill_switch_active",
    "activate_global_kill_switch",
    "deactivate_global_kill_switch",
    "activate_tenant_kill_switch",
    "deactivate_tenant_kill_switch",
    "activate_capability_kill_switch",
    "deactivate_capability_kill_switch",
    "require_kill_switch_inactive",
    # Audit Service
    "AuditService",
    "AuditContext",
    "ModelContext",
    "PolicyContext",
    "AuditEntry",
    "IncidentBundle",
    "get_audit_service",
    "REQUIRED_BASE_FIELDS",
    "REQUIRED_REQUEST_FIELDS",
    "REQUIRED_ACTION_FIELDS",
    "REQUIRED_EXECUTION_FIELDS",
    "REQUIRED_MODEL_FIELDS",
    # Data Retention
    "DataRetentionService",
    "DeletionRequest",
    "DeletionStatus",
    "DeletionScope",
    "RetentionPurgeResult",
    "get_data_retention_service",
    "reset_data_retention_service",
    # Prompt Anonymizer
    "PromptAnonymizer",
    "AnonymizedPrompt",
    "AnonymizedPromptStore",
    "AnonymizationLevel",
    "AnonymizationResult",
    "get_prompt_anonymizer",
    "get_anonymized_prompt_store",
    "anonymize_prompt",
    "reset_anonymizer_singletons",
    # Metrics
    "MetricsCollector",
    "MetricType",
    "MetricDataPoint",
    "LatencyStats",
    "RateStats",
    "ApprovalStats",
    "QuotaStats",
    "SLAMetrics",
    "get_metrics_collector",
    "record_inference_latency",
    "record_intent_latency",
    "record_planning_latency",
    "record_execution_latency",
    "record_success",
    "record_error",
    "record_timeout",
    "record_approval_granted",
    "record_approval_rejected",
    "record_auto_approved",
    "record_quota_rejected",
    "record_rate_limited",
    "record_circuit_breaker_open",
    "timed_operation",
    "TimingContext",
    # Alerting
    "AlertingService",
    "AlertSeverity",
    "AlertType",
    "AlertThresholds",
    "Alert",
    "get_alerting_service",
    "check_and_alert",
    "emit_circuit_breaker_alert",
]
