/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear Admin API
 * API for X-Ear Admin Panel
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminTickets200,
  GetAdminTicketsParams,
  PutAdminTicketsIdBody,
  SupportTicketInput
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * @summary List Support Tickets
 */
export const getAdminTickets = (
    params?: GetAdminTicketsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<GetAdminTickets200>(
      {url: `/admin/tickets`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAdminTicketsQueryKey = (params?: GetAdminTicketsParams,) => {
    return [
    `/admin/tickets`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminTicketsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTickets>>, TError = unknown>(params?: GetAdminTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTicketsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTickets>>> = ({ signal }) => getAdminTickets(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTickets>>>
export type GetAdminTicketsQueryError = unknown


export function useGetAdminTickets<TData = Awaited<ReturnType<typeof getAdminTickets>>, TError = unknown>(
 params: undefined |  GetAdminTicketsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTickets>>,
          TError,
          Awaited<ReturnType<typeof getAdminTickets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTickets<TData = Awaited<ReturnType<typeof getAdminTickets>>, TError = unknown>(
 params?: GetAdminTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTickets>>,
          TError,
          Awaited<ReturnType<typeof getAdminTickets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminTickets<TData = Awaited<ReturnType<typeof getAdminTickets>>, TError = unknown>(
 params?: GetAdminTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Support Tickets
 */

export function useGetAdminTickets<TData = Awaited<ReturnType<typeof getAdminTickets>>, TError = unknown>(
 params?: GetAdminTicketsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTickets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminTicketsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Support Ticket
 */
export const postAdminTickets = (
    supportTicketInput: SupportTicketInput,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/admin/tickets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: supportTicketInput, signal
    },
      );
    }
  


export const getPostAdminTicketsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTickets>>, TError,{data: SupportTicketInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAdminTickets>>, TError,{data: SupportTicketInput}, TContext> => {

const mutationKey = ['postAdminTickets'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminTickets>>, {data: SupportTicketInput}> = (props) => {
          const {data} = props ?? {};

          return  postAdminTickets(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminTicketsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminTickets>>>
    export type PostAdminTicketsMutationBody = SupportTicketInput
    export type PostAdminTicketsMutationError = unknown

    /**
 * @summary Create Support Ticket
 */
export const usePostAdminTickets = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminTickets>>, TError,{data: SupportTicketInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminTickets>>,
        TError,
        {data: SupportTicketInput},
        TContext
      > => {

      const mutationOptions = getPostAdminTicketsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Support Ticket
 */
export const putAdminTicketsId = (
    id: string,
    putAdminTicketsIdBody: PutAdminTicketsIdBody,
 ) => {
      
      
      return adminApi<void>(
      {url: `/admin/tickets/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putAdminTicketsIdBody
    },
      );
    }
  


export const getPutAdminTicketsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminTicketsId>>, TError,{id: string;data: PutAdminTicketsIdBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAdminTicketsId>>, TError,{id: string;data: PutAdminTicketsIdBody}, TContext> => {

const mutationKey = ['putAdminTicketsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAdminTicketsId>>, {id: string;data: PutAdminTicketsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putAdminTicketsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutAdminTicketsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putAdminTicketsId>>>
    export type PutAdminTicketsIdMutationBody = PutAdminTicketsIdBody
    export type PutAdminTicketsIdMutationError = unknown

    /**
 * @summary Update Support Ticket
 */
export const usePutAdminTicketsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminTicketsId>>, TError,{id: string;data: PutAdminTicketsIdBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAdminTicketsId>>,
        TError,
        {id: string;data: PutAdminTicketsIdBody},
        TContext
      > => {

      const mutationOptions = getPutAdminTicketsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    