/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminBirfaturaInvoicesParams,
  GetAdminLogsParams,
  HTTPValidationError,
  ResponseEnvelopeBirFaturaInvoicesResponse,
  ResponseEnvelopeBirFaturaLogsResponse,
  ResponseEnvelopeBirFaturaStats
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * Get BirFatura statistics
 * @summary Get Stats
 */
export const getAdminStats = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<ResponseEnvelopeBirFaturaStats>(
      {url: `/api/admin/birfatura/stats`, method: 'GET', signal
    },
      );
    }
  



export const getGetAdminStatsQueryKey = () => {
    return [
    `/api/admin/birfatura/stats`
    ] as const;
    }

    
export const getGetAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStats>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({ signal }) => getAdminStats(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStats>>>
export type GetAdminStatsQueryError = unknown


export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Stats
 */

export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get invoices with BirFatura status
 * @summary Get Invoices
 */
export const getAdminBirfaturaInvoices = (
    params?: GetAdminBirfaturaInvoicesParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<ResponseEnvelopeBirFaturaInvoicesResponse>(
      {url: `/api/admin/birfatura/invoices`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAdminBirfaturaInvoicesQueryKey = (params?: GetAdminBirfaturaInvoicesParams,) => {
    return [
    `/api/admin/birfatura/invoices`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminBirfaturaInvoicesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError = HTTPValidationError>(params?: GetAdminBirfaturaInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminBirfaturaInvoicesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>> = ({ signal }) => getAdminBirfaturaInvoices(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminBirfaturaInvoicesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>>
export type GetAdminBirfaturaInvoicesQueryError = HTTPValidationError


export function useGetAdminBirfaturaInvoices<TData = Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError = HTTPValidationError>(
 params: undefined |  GetAdminBirfaturaInvoicesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>,
          TError,
          Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminBirfaturaInvoices<TData = Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError = HTTPValidationError>(
 params?: GetAdminBirfaturaInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>,
          TError,
          Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminBirfaturaInvoices<TData = Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError = HTTPValidationError>(
 params?: GetAdminBirfaturaInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Invoices
 */

export function useGetAdminBirfaturaInvoices<TData = Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError = HTTPValidationError>(
 params?: GetAdminBirfaturaInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBirfaturaInvoices>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminBirfaturaInvoicesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get BirFatura related logs
 * @summary Get Logs
 */
export const getAdminLogs = (
    params?: GetAdminLogsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<ResponseEnvelopeBirFaturaLogsResponse>(
      {url: `/api/admin/birfatura/logs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAdminLogsQueryKey = (params?: GetAdminLogsParams,) => {
    return [
    `/api/admin/birfatura/logs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminLogsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminLogs>>, TError = HTTPValidationError>(params?: GetAdminLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminLogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminLogs>>> = ({ signal }) => getAdminLogs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminLogs>>>
export type GetAdminLogsQueryError = HTTPValidationError


export function useGetAdminLogs<TData = Awaited<ReturnType<typeof getAdminLogs>>, TError = HTTPValidationError>(
 params: undefined |  GetAdminLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLogs>>,
          TError,
          Awaited<ReturnType<typeof getAdminLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLogs<TData = Awaited<ReturnType<typeof getAdminLogs>>, TError = HTTPValidationError>(
 params?: GetAdminLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminLogs>>,
          TError,
          Awaited<ReturnType<typeof getAdminLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminLogs<TData = Awaited<ReturnType<typeof getAdminLogs>>, TError = HTTPValidationError>(
 params?: GetAdminLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Logs
 */

export function useGetAdminLogs<TData = Awaited<ReturnType<typeof getAdminLogs>>, TError = HTTPValidationError>(
 params?: GetAdminLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminLogs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




