/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  SuccessResponse,
  Supplier,
  SuppliersAcceptSuggestedSupplier200,
  SuppliersAcceptSuggestedSupplier201,
  SuppliersCreateSupplierBody,
  SuppliersGetSuggestedSuppliers200,
  SuppliersGetSupplierInvoices200,
  SuppliersGetSupplierInvoicesParams,
  SuppliersGetSuppliers200,
  SuppliersGetSuppliersParams,
  SuppliersRejectSuggestedSupplier200
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Retrieve a list of suppliers with optional filtering and pagination
 * @summary Get list of suppliers
 */
export const suppliersGetSuppliers = (
    params?: SuppliersGetSuppliersParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<SuppliersGetSuppliers200>(
      {url: `/api/suppliers`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSuppliersGetSuppliersQueryKey = (params?: SuppliersGetSuppliersParams,) => {
    return [
    `/api/suppliers`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSuppliersGetSuppliersQueryOptions = <TData = Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError = ErrorResponse>(params?: SuppliersGetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersGetSuppliersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersGetSuppliers>>> = ({ signal }) => suppliersGetSuppliers(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SuppliersGetSuppliersQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersGetSuppliers>>>
export type SuppliersGetSuppliersQueryError = ErrorResponse


export function useSuppliersGetSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError = ErrorResponse>(
 params: undefined |  SuppliersGetSuppliersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSuppliers>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError = ErrorResponse>(
 params?: SuppliersGetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSuppliers>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError = ErrorResponse>(
 params?: SuppliersGetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get list of suppliers
 */

export function useSuppliersGetSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError = ErrorResponse>(
 params?: SuppliersGetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSuppliersGetSuppliersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Register a new supplier with contact and business information
 * @summary Create a new supplier
 */
export const suppliersCreateSupplier = (
    suppliersCreateSupplierBody?: SuppliersCreateSupplierBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<Supplier>(
      {url: `/api/suppliers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suppliersCreateSupplierBody, signal
    },
      );
    }
  


export const getSuppliersCreateSupplierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersCreateSupplier>>, TError,{data: SuppliersCreateSupplierBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof suppliersCreateSupplier>>, TError,{data: SuppliersCreateSupplierBody}, TContext> => {

const mutationKey = ['suppliersCreateSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersCreateSupplier>>, {data: SuppliersCreateSupplierBody}> = (props) => {
          const {data} = props ?? {};

          return  suppliersCreateSupplier(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SuppliersCreateSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersCreateSupplier>>>
    export type SuppliersCreateSupplierMutationBody = SuppliersCreateSupplierBody
    export type SuppliersCreateSupplierMutationError = unknown

    /**
 * @summary Create a new supplier
 */
export const useSuppliersCreateSupplier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersCreateSupplier>>, TError,{data: SuppliersCreateSupplierBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersCreateSupplier>>,
        TError,
        {data: SuppliersCreateSupplierBody},
        TContext
      > => {

      const mutationOptions = getSuppliersCreateSupplierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove a supplier from the system
 * @summary Delete a supplier (soft delete by setting is_active=False)
 */
export const suppliersDeleteSupplier = (
    supplierId: string,
 ) => {
      
      
      return adminApi<SuccessResponse>(
      {url: `/api/suppliers/${supplierId}`, method: 'DELETE'
    },
      );
    }
  


export const getSuppliersDeleteSupplierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersDeleteSupplier>>, TError,{supplierId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof suppliersDeleteSupplier>>, TError,{supplierId: string}, TContext> => {

const mutationKey = ['suppliersDeleteSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersDeleteSupplier>>, {supplierId: string}> = (props) => {
          const {supplierId} = props ?? {};

          return  suppliersDeleteSupplier(supplierId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SuppliersDeleteSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersDeleteSupplier>>>
    
    export type SuppliersDeleteSupplierMutationError = unknown

    /**
 * @summary Delete a supplier (soft delete by setting is_active=False)
 */
export const useSuppliersDeleteSupplier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersDeleteSupplier>>, TError,{supplierId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersDeleteSupplier>>,
        TError,
        {supplierId: string},
        TContext
      > => {

      const mutationOptions = getSuppliersDeleteSupplierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get list of products available from a specific supplier
 * @summary Get all products for a specific supplier
 */
export const suppliersGetSupplierProducts = (
    supplierId: string,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/suppliers/${supplierId}/products`, method: 'GET', signal
    },
      );
    }
  



export const getSuppliersGetSupplierProductsQueryKey = (supplierId?: string,) => {
    return [
    `/api/suppliers/${supplierId}/products`
    ] as const;
    }

    
export const getSuppliersGetSupplierProductsQueryOptions = <TData = Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError = unknown>(supplierId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersGetSupplierProductsQueryKey(supplierId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>> = ({ signal }) => suppliersGetSupplierProducts(supplierId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(supplierId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SuppliersGetSupplierProductsQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>>
export type SuppliersGetSupplierProductsQueryError = unknown


export function useSuppliersGetSupplierProducts<TData = Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError = unknown>(
 supplierId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierProducts>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierProducts<TData = Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError = unknown>(
 supplierId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierProducts>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierProducts<TData = Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError = unknown>(
 supplierId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all products for a specific supplier
 */

export function useSuppliersGetSupplierProducts<TData = Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError = unknown>(
 supplierId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSuppliersGetSupplierProductsQueryOptions(supplierId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get supplier statistics including order history
 * @summary Get supplier statistics
 */
export const suppliersGetSupplierStats = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/suppliers/stats`, method: 'GET', signal
    },
      );
    }
  



export const getSuppliersGetSupplierStatsQueryKey = () => {
    return [
    `/api/suppliers/stats`
    ] as const;
    }

    
export const getSuppliersGetSupplierStatsQueryOptions = <TData = Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersGetSupplierStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersGetSupplierStats>>> = ({ signal }) => suppliersGetSupplierStats(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SuppliersGetSupplierStatsQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersGetSupplierStats>>>
export type SuppliersGetSupplierStatsQueryError = unknown


export function useSuppliersGetSupplierStats<TData = Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierStats>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierStats<TData = Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierStats>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierStats<TData = Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get supplier statistics
 */

export function useSuppliersGetSupplierStats<TData = Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSuppliersGetSupplierStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve purchase invoices for the specified supplier
 * @summary Get supplier purchase invoices (incoming and outgoing)
 */
export const suppliersGetSupplierInvoices = (
    supplierId: string,
    params?: SuppliersGetSupplierInvoicesParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<SuppliersGetSupplierInvoices200>(
      {url: `/api/suppliers/${supplierId}/invoices`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSuppliersGetSupplierInvoicesQueryKey = (supplierId?: string,
    params?: SuppliersGetSupplierInvoicesParams,) => {
    return [
    `/api/suppliers/${supplierId}/invoices`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSuppliersGetSupplierInvoicesQueryOptions = <TData = Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError = ErrorResponse>(supplierId: string,
    params?: SuppliersGetSupplierInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersGetSupplierInvoicesQueryKey(supplierId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>> = ({ signal }) => suppliersGetSupplierInvoices(supplierId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(supplierId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SuppliersGetSupplierInvoicesQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>>
export type SuppliersGetSupplierInvoicesQueryError = ErrorResponse


export function useSuppliersGetSupplierInvoices<TData = Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError = ErrorResponse>(
 supplierId: string,
    params: undefined |  SuppliersGetSupplierInvoicesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierInvoices<TData = Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError = ErrorResponse>(
 supplierId: string,
    params?: SuppliersGetSupplierInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSupplierInvoices<TData = Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError = ErrorResponse>(
 supplierId: string,
    params?: SuppliersGetSupplierInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get supplier purchase invoices (incoming and outgoing)
 */

export function useSuppliersGetSupplierInvoices<TData = Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError = ErrorResponse>(
 supplierId: string,
    params?: SuppliersGetSupplierInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSupplierInvoices>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSuppliersGetSupplierInvoicesQueryOptions(supplierId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retrieve a list of suggested suppliers based on incoming invoices
 * @summary Get suggested suppliers (pending approval)
 */
export const suppliersGetSuggestedSuppliers = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<SuppliersGetSuggestedSuppliers200>(
      {url: `/api/suppliers/suggested`, method: 'GET', signal
    },
      );
    }
  



export const getSuppliersGetSuggestedSuppliersQueryKey = () => {
    return [
    `/api/suppliers/suggested`
    ] as const;
    }

    
export const getSuppliersGetSuggestedSuppliersQueryOptions = <TData = Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSuppliersGetSuggestedSuppliersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>> = ({ signal }) => suppliersGetSuggestedSuppliers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SuppliersGetSuggestedSuppliersQueryResult = NonNullable<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>>
export type SuppliersGetSuggestedSuppliersQueryError = ErrorResponse


export function useSuppliersGetSuggestedSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSuggestedSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>,
          TError,
          Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSuppliersGetSuggestedSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get suggested suppliers (pending approval)
 */

export function useSuppliersGetSuggestedSuppliers<TData = Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof suppliersGetSuggestedSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSuppliersGetSuggestedSuppliersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Accept a suggested supplier and create or link to a supplier by tax number
 * @summary Accept suggested supplier and create/link supplier record
 */
export const suppliersAcceptSuggestedSupplier = (
    suggestedId: string,
 signal?: AbortSignal
) => {
      
      
      return adminApi<SuppliersAcceptSuggestedSupplier200 | SuppliersAcceptSuggestedSupplier201>(
      {url: `/api/suppliers/suggested/${suggestedId}/accept`, method: 'POST', signal
    },
      );
    }
  


export const getSuppliersAcceptSuggestedSupplierMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>, TError,{suggestedId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>, TError,{suggestedId: string}, TContext> => {

const mutationKey = ['suppliersAcceptSuggestedSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>, {suggestedId: string}> = (props) => {
          const {suggestedId} = props ?? {};

          return  suppliersAcceptSuggestedSupplier(suggestedId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SuppliersAcceptSuggestedSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>>
    
    export type SuppliersAcceptSuggestedSupplierMutationError = ErrorResponse

    /**
 * @summary Accept suggested supplier and create/link supplier record
 */
export const useSuppliersAcceptSuggestedSupplier = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>, TError,{suggestedId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersAcceptSuggestedSupplier>>,
        TError,
        {suggestedId: string},
        TContext
      > => {

      const mutationOptions = getSuppliersAcceptSuggestedSupplierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reject and mark a suggested supplier as rejected
 * @summary Reject a suggested supplier
 */
export const suppliersRejectSuggestedSupplier = (
    suggestedId: string,
 ) => {
      
      
      return adminApi<SuppliersRejectSuggestedSupplier200>(
      {url: `/api/suppliers/suggested/${suggestedId}`, method: 'DELETE'
    },
      );
    }
  


export const getSuppliersRejectSuggestedSupplierMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>, TError,{suggestedId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>, TError,{suggestedId: string}, TContext> => {

const mutationKey = ['suppliersRejectSuggestedSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>, {suggestedId: string}> = (props) => {
          const {suggestedId} = props ?? {};

          return  suppliersRejectSuggestedSupplier(suggestedId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SuppliersRejectSuggestedSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>>
    
    export type SuppliersRejectSuggestedSupplierMutationError = ErrorResponse

    /**
 * @summary Reject a suggested supplier
 */
export const useSuppliersRejectSuggestedSupplier = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>, TError,{suggestedId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof suppliersRejectSuggestedSupplier>>,
        TError,
        {suggestedId: string},
        TContext
      > => {

      const mutationOptions = getSuppliersRejectSuggestedSupplierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    