/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RegistrationVerifyRegistrationOtpBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Create new verify-registration-otp
 * @summary POST /api/verify-registration-otp
 */
export const registrationVerifyRegistrationOtp = (
    registrationVerifyRegistrationOtpBody?: RegistrationVerifyRegistrationOtpBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/api/verify-registration-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registrationVerifyRegistrationOtpBody, signal
    },
      );
    }
  


export const getRegistrationVerifyRegistrationOtpMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>, TError,{data: RegistrationVerifyRegistrationOtpBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>, TError,{data: RegistrationVerifyRegistrationOtpBody}, TContext> => {

const mutationKey = ['registrationVerifyRegistrationOtp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>, {data: RegistrationVerifyRegistrationOtpBody}> = (props) => {
          const {data} = props ?? {};

          return  registrationVerifyRegistrationOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegistrationVerifyRegistrationOtpMutationResult = NonNullable<Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>>
    export type RegistrationVerifyRegistrationOtpMutationBody = RegistrationVerifyRegistrationOtpBody
    export type RegistrationVerifyRegistrationOtpMutationError = unknown

    /**
 * @summary POST /api/verify-registration-otp
 */
export const useRegistrationVerifyRegistrationOtp = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>, TError,{data: RegistrationVerifyRegistrationOtpBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registrationVerifyRegistrationOtp>>,
        TError,
        {data: RegistrationVerifyRegistrationOtpBody},
        TContext
      > => {

      const mutationOptions = getRegistrationVerifyRegistrationOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    