"""add posts table

Revision ID: 702711ef7caf
Revises: 20260306_154345
Create Date: 2026-03-06 16:06:12.418568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702711ef7caf'
down_revision: Union[str, None] = '20260306_154345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)
        batch_op.create_index('ix_posts_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index('ix_posts_published_slug', ['is_published', 'slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)

    # Wrap ai_requests in batch mode
    with op.batch_alter_table('ai_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('intent_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('intent_confidence',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('model_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('model_version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('prompt_template_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('tokens_input',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('tokens_output',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    # Create indexes idempotently (may already exist from initial schema)
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_legal_hold ON ai_requests (legal_hold)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_legal_hold_created ON ai_requests (legal_hold, created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_prompt_hash ON ai_requests (prompt_hash)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_status_created ON ai_requests (status, created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_tenant_created ON ai_requests (tenant_id, created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_ai_requests_user_created ON ai_requests (user_id, created_at)')

    # Wrap bulk_import_batches
    with op.batch_alter_table('bulk_import_batches', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bulk_import_batches_tenant') THEN
                ALTER TABLE bulk_import_batches ADD CONSTRAINT fk_bulk_import_batches_tenant
                    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # Wrap bulk_import_records
    with op.batch_alter_table('bulk_import_records', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('batch_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bulk_import_records_tenant') THEN
                ALTER TABLE bulk_import_records ADD CONSTRAINT fk_bulk_import_records_tenant
                    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # Drop columns idempotently (may not exist on fresh DBs from initial schema)
    for col in ['model', 'barcode', 'brand']:
        op.execute(f"ALTER TABLE device_assignments DROP COLUMN IF EXISTS {col}")

    # Create indexes idempotently
    # Only create index if column exists (may not on fresh DBs)
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name='purchase_invoices' AND column_name='purchase_id') THEN
                EXECUTE 'CREATE INDEX IF NOT EXISTS ix_purchase_invoices_purchase_id ON purchase_invoices (purchase_id)';
            END IF;
        END $$;
    """)
    op.execute('CREATE INDEX IF NOT EXISTS ix_purchases_purchase_date ON purchases (purchase_date)')

    # Foreign keys idempotently
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_purchases_tenant') THEN
                ALTER TABLE purchases ADD CONSTRAINT fk_purchases_tenant
                    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # Drop tenant columns idempotently
    for col in ['tax_office', 'phone', 'email', 'city', 'address', 'tax_number']:
        op.execute(f"ALTER TABLE tenants DROP COLUMN IF EXISTS {col}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Minimal downgrade for speed and safety in SQLite
    op.drop_table('posts')
