"""add_sequences_table_back

Revision ID: ef70430aa16e
Revises: 07f67ca724f5
Create Date: 2026-02-09 14:39:35.000375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef70430aa16e'
down_revision: Union[str, None] = '07f67ca724f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('seq_type', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'seq_type', 'year', 'prefix', name='uq_sequence_key')
    )
    op.create_index(op.f('ix_sequences_tenant_id'), 'sequences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_tenant_id'), table_name='sequences')
    op.drop_table('sequences')
    # ### end Alembic commands ###
