/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ResponseEnvelopeListUnionDeviceAssignmentUpdateInstallmentPaymentPasswordChangeRequestPatientSearchFiltersPaymentPlanCreatePermissionReadSMSHeaderRequestUpdateSMSLogReadSMSProviderConfigCreateTenantStatsUserProfile
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * This endpoint exists solely to force Pydantic to generate OpenAPI schemas 
for models that are required by the frontend/SDK but not yet used 
in active API endpoints.
 * @summary Schema Registry
 */
export const schemaRegistry = (
    
 signal?: AbortSignal
) => {
      
      
      return adminApi<ResponseEnvelopeListUnionDeviceAssignmentUpdateInstallmentPaymentPasswordChangeRequestPatientSearchFiltersPaymentPlanCreatePermissionReadSMSHeaderRequestUpdateSMSLogReadSMSProviderConfigCreateTenantStatsUserProfile>(
      {url: `/api/developer/schema-registry`, method: 'GET', signal
    },
      );
    }
  



export const getSchemaRegistryQueryKey = () => {
    return [
    `/api/developer/schema-registry`
    ] as const;
    }

    
export const getSchemaRegistryQueryOptions = <TData = Awaited<ReturnType<typeof schemaRegistry>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSchemaRegistryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof schemaRegistry>>> = ({ signal }) => schemaRegistry(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SchemaRegistryQueryResult = NonNullable<Awaited<ReturnType<typeof schemaRegistry>>>
export type SchemaRegistryQueryError = unknown


export function useSchemaRegistry<TData = Awaited<ReturnType<typeof schemaRegistry>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schemaRegistry>>,
          TError,
          Awaited<ReturnType<typeof schemaRegistry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSchemaRegistry<TData = Awaited<ReturnType<typeof schemaRegistry>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schemaRegistry>>,
          TError,
          Awaited<ReturnType<typeof schemaRegistry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSchemaRegistry<TData = Awaited<ReturnType<typeof schemaRegistry>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Schema Registry
 */

export function useSchemaRegistry<TData = Awaited<ReturnType<typeof schemaRegistry>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRegistry>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSchemaRegistryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




