/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear Admin API
 * API for X-Ear Admin Panel
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CampaignInput,
  GetAdminCampaigns200,
  GetAdminCampaignsId200,
  GetAdminCampaignsParams,
  PostAdminCampaigns201,
  PutAdminCampaignsId200
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * @summary List Campaigns
 */
export const getAdminCampaigns = (
    params?: GetAdminCampaignsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<GetAdminCampaigns200>(
      {url: `/admin/campaigns`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAdminCampaignsQueryKey = (params?: GetAdminCampaignsParams,) => {
    return [
    `/admin/campaigns`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAdminCampaignsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCampaigns>>, TError = unknown>(params?: GetAdminCampaignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCampaignsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCampaigns>>> = ({ signal }) => getAdminCampaigns(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminCampaignsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCampaigns>>>
export type GetAdminCampaignsQueryError = unknown


export function useGetAdminCampaigns<TData = Awaited<ReturnType<typeof getAdminCampaigns>>, TError = unknown>(
 params: undefined |  GetAdminCampaignsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCampaigns>>,
          TError,
          Awaited<ReturnType<typeof getAdminCampaigns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminCampaigns<TData = Awaited<ReturnType<typeof getAdminCampaigns>>, TError = unknown>(
 params?: GetAdminCampaignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCampaigns>>,
          TError,
          Awaited<ReturnType<typeof getAdminCampaigns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminCampaigns<TData = Awaited<ReturnType<typeof getAdminCampaigns>>, TError = unknown>(
 params?: GetAdminCampaignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Campaigns
 */

export function useGetAdminCampaigns<TData = Awaited<ReturnType<typeof getAdminCampaigns>>, TError = unknown>(
 params?: GetAdminCampaignsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaigns>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminCampaignsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Campaign
 */
export const postAdminCampaigns = (
    campaignInput: CampaignInput,
 signal?: AbortSignal
) => {
      
      
      return adminApi<PostAdminCampaigns201>(
      {url: `/admin/campaigns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campaignInput, signal
    },
      );
    }
  


export const getPostAdminCampaignsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminCampaigns>>, TError,{data: CampaignInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAdminCampaigns>>, TError,{data: CampaignInput}, TContext> => {

const mutationKey = ['postAdminCampaigns'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminCampaigns>>, {data: CampaignInput}> = (props) => {
          const {data} = props ?? {};

          return  postAdminCampaigns(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAdminCampaignsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminCampaigns>>>
    export type PostAdminCampaignsMutationBody = CampaignInput
    export type PostAdminCampaignsMutationError = unknown

    /**
 * @summary Create Campaign
 */
export const usePostAdminCampaigns = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminCampaigns>>, TError,{data: CampaignInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminCampaigns>>,
        TError,
        {data: CampaignInput},
        TContext
      > => {

      const mutationOptions = getPostAdminCampaignsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Campaign Details
 */
export const getAdminCampaignsId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return adminApi<GetAdminCampaignsId200>(
      {url: `/admin/campaigns/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetAdminCampaignsIdQueryKey = (id?: number,) => {
    return [
    `/admin/campaigns/${id}`
    ] as const;
    }

    
export const getGetAdminCampaignsIdQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCampaignsId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCampaignsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCampaignsId>>> = ({ signal }) => getAdminCampaignsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAdminCampaignsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCampaignsId>>>
export type GetAdminCampaignsIdQueryError = unknown


export function useGetAdminCampaignsId<TData = Awaited<ReturnType<typeof getAdminCampaignsId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCampaignsId>>,
          TError,
          Awaited<ReturnType<typeof getAdminCampaignsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminCampaignsId<TData = Awaited<ReturnType<typeof getAdminCampaignsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCampaignsId>>,
          TError,
          Awaited<ReturnType<typeof getAdminCampaignsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAdminCampaignsId<TData = Awaited<ReturnType<typeof getAdminCampaignsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Campaign Details
 */

export function useGetAdminCampaignsId<TData = Awaited<ReturnType<typeof getAdminCampaignsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCampaignsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAdminCampaignsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Campaign
 */
export const putAdminCampaignsId = (
    id: number,
    campaignInput: CampaignInput,
 ) => {
      
      
      return adminApi<PutAdminCampaignsId200>(
      {url: `/admin/campaigns/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: campaignInput
    },
      );
    }
  


export const getPutAdminCampaignsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminCampaignsId>>, TError,{id: number;data: CampaignInput}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAdminCampaignsId>>, TError,{id: number;data: CampaignInput}, TContext> => {

const mutationKey = ['putAdminCampaignsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAdminCampaignsId>>, {id: number;data: CampaignInput}> = (props) => {
          const {id,data} = props ?? {};

          return  putAdminCampaignsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutAdminCampaignsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putAdminCampaignsId>>>
    export type PutAdminCampaignsIdMutationBody = CampaignInput
    export type PutAdminCampaignsIdMutationError = unknown

    /**
 * @summary Update Campaign
 */
export const usePutAdminCampaignsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminCampaignsId>>, TError,{id: number;data: CampaignInput}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAdminCampaignsId>>,
        TError,
        {id: number;data: CampaignInput},
        TContext
      > => {

      const mutationOptions = getPutAdminCampaignsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Campaign
 */
export const deleteAdminCampaignsId = (
    id: number,
 ) => {
      
      
      return adminApi<void>(
      {url: `/admin/campaigns/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteAdminCampaignsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCampaignsId>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCampaignsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminCampaignsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminCampaignsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminCampaignsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminCampaignsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminCampaignsId>>>
    
    export type DeleteAdminCampaignsIdMutationError = unknown

    /**
 * @summary Delete Campaign
 */
export const useDeleteAdminCampaignsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCampaignsId>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminCampaignsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAdminCampaignsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    