import { create } from 'zustand';
// We assume these types will be generated by Orval. 
// If not yet available, we will rely on TS inference or temporary any until generation completes.
import type {
    EntityItem,
    Capability,
    SlotConfig,
    ExecuteResponse
} from '../api/generated/schemas';

// Define modes for the state machine
export type ComposerMode = 'idle' | 'context_locked' | 'action_selection' | 'slot_filling' | 'confirmation' | 'executing';

interface ComposerState {
    isOpen: boolean; // Global visibility
    mode: ComposerMode;

    // Query state
    query: string;

    // Context State
    context: EntityItem[] | null;

    // Action State
    availableActions: Capability[];
    selectedAction: Capability | null;

    // Slot State
    slots: Record<string, unknown>; // Collected arguments
    currentSlot: SlotConfig | null; // The slot currently being asked

    // Execution State
    isDryRun: boolean;
    executionResult: ExecuteResponse | null;

    // Actions
    setOpen: (open: boolean) => void;
    toggleOpen: () => void;

    setQuery: (q: string) => void;
    setContext: (entities: EntityItem[] | null) => void;
    setAvailableActions: (actions: Capability[]) => void;
    selectAction: (action: Capability, entities?: EntityItem[]) => void;
    startWithCommand: (prompt: string, entities: EntityItem[]) => void;

    updateSlot: (key: string, value: unknown) => void;
    nextSlot: () => void; // Advances to next slot or confirmation

    reset: () => void;
    setExecutionResult: (res: ExecuteResponse) => void;

    // Execution Progress State
    executionSteps: ExecutionStep[];
    executionStatus: ExecutionStatus;
    executionError: string | null;

    setExecutionStatus: (status: ExecutionStatus) => void;
    addExecutionStep: (step: ExecutionStep) => void;
    updateExecutionStep: (id: string, updates: Partial<ExecutionStep>) => void;
    setExecutionError: (error: string | null) => void;
    setPlan: (plan: any) => void;
}

export type ExecutionStatus = 'idle' | 'init' | 'running' | 'waiting' | 'success' | 'error';

export interface ExecutionStep {
    id: string;
    label: string;
    status: 'pending' | 'running' | 'completed' | 'failed';
}

export const useComposerStore = create<ComposerState>((set, get) => ({
    isOpen: false,
    mode: 'idle',
    query: '',
    context: null,
    availableActions: [],
    selectedAction: null,
    slots: {},
    currentSlot: null,
    isDryRun: false,
    executionResult: null,
    executionSteps: [],
    executionStatus: 'idle',
    executionError: null,

    setOpen: (open) => set({ isOpen: open }),
    toggleOpen: () => set((state) => ({ isOpen: !state.isOpen })),

    setQuery: (q) => set({ query: q }),

    setContext: (entities) => set({
        context: entities,
        mode: (entities && entities.length > 0) ? 'context_locked' : 'idle',
        query: '',
        selectedAction: null,
        slots: {}
    }),

    setAvailableActions: (actions) => set({ availableActions: actions }),

    selectAction: (action, entities) => {
        const currentState = get();
        const initialSlots: Record<string, unknown> = {};

        // Unified source for entities (either passed or from context)
        const sourceEntities = entities || currentState.context || [];

        // Map all source entities to available slots
        sourceEntities.forEach(entity => {
            const matchingSlot = action.slots?.find(s => {
                // Map context type to slot name conventions
                // legacy: patient_id compatibility for backward compatibility with old actions
                if (entity.type === 'patient' && (s.name === 'party_id' || s.name === 'patient_id')) return true; // legacy
                if (entity.type === 'device' && (s.name === 'device_id' || s.name === 'inventory_id')) return true;
                if (entity.type === 'invoice' && s.name === 'invoice_id') return true;
                if (entity.type === 'supplier' && s.name === 'supplier_id') return true;
                return false;
            });

            if (matchingSlot) {
                initialSlots[matchingSlot.name] = entity.id;
                initialSlots[`_${matchingSlot.name}_label`] = entity.label;
            }
        });

        set({
            selectedAction: action,
            slots: initialSlots,
            mode: 'slot_filling'
        });

        // Initialize first slot
        const state = get();
        state.nextSlot();
    },

    updateSlot: (key, value) => {
        set((state) => ({
            slots: { ...state.slots, [key]: value }
        }));
    },

    nextSlot: () => {
        const { selectedAction, slots } = get();
        if (!selectedAction) return;

        // Find first missing slot
        const requiredSlots = selectedAction.slots || [];
        const nextMissing = requiredSlots.find(s => {
            const isOptional = s.validationRules?.required === false;
            const val = slots[s.name];
            const isMissing = val === undefined || val === null || val === '';
            return isMissing && !isOptional;
        });

        if (nextMissing) {
            set({ currentSlot: nextMissing, mode: 'slot_filling' });
        } else {
            // All slots filled
            set({ currentSlot: null, mode: 'confirmation' });
        }
    },

    reset: () => set({
        mode: 'idle',
        query: '',
        context: null,
        selectedAction: null,
        slots: {},
        currentSlot: null,
        executionResult: null,
        executionSteps: [],
        executionStatus: 'idle',
        executionError: null
    }),

    setExecutionResult: (res) => set({ executionResult: res }),

    // Execution Progress Actions
    setExecutionStatus: (status) => set({ executionStatus: status, mode: status === 'running' ? 'executing' : get().mode }),

    addExecutionStep: (step) => set((state) => ({
        executionSteps: [...state.executionSteps, step]
    })),

    updateExecutionStep: (id, updates) => set((state) => ({
        executionSteps: state.executionSteps.map(s => s.id === id ? { ...s, ...updates } : s)
    })),

    setExecutionError: (error) => set({ executionError: error }),

    startWithCommand: (prompt, entities) => {
        set({
            context: entities,
            query: prompt,
            mode: 'idle', // Chat will handle the rest
            isOpen: false
        });
    },

    setPlan: (plan) => {
        if (!plan) return;

        // Map first step as selected action for simplified view
        const firstStep = plan.steps[0];

        // Convert Steps to ExecutionSteps for progress UI
        const executionSteps: ExecutionStep[] = plan.steps.map((s: any) => ({
            id: `step-${s.stepNumber}`,
            label: s.description,
            status: 'pending'
        }));

        set({
            selectedAction: {
                name: firstStep.toolName,
                description: firstStep.description,
                slots: [] // Handled by chat
            } as any,
            executionSteps,
            executionStatus: 'waiting', // Waiting for user confirmation
            mode: 'confirmation',
            slots: firstStep.parameters || {}
        });
    }
}));
