/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API (auto-generated)
 * X-Ear CRM API for managing patients, devices, appointments, sales, and more
 * OpenAPI spec version: 0.0.0-auto
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OcrCalculateSimilarityBody
} from '../index.schemas';

import { adminApi } from '../../apiMutator';




/**
 * Calculate similarity between documents using OCR text analysis
 * @summary Calculate similarity between two images using OCR text
 */
export const ocrCalculateSimilarity = (
    ocrCalculateSimilarityBody?: OcrCalculateSimilarityBody,
 signal?: AbortSignal
) => {
      
      
      return adminApi<void>(
      {url: `/similarity`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ocrCalculateSimilarityBody, signal
    },
      );
    }
  


export const getOcrCalculateSimilarityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrCalculateSimilarity>>, TError,{data: OcrCalculateSimilarityBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof ocrCalculateSimilarity>>, TError,{data: OcrCalculateSimilarityBody}, TContext> => {

const mutationKey = ['ocrCalculateSimilarity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ocrCalculateSimilarity>>, {data: OcrCalculateSimilarityBody}> = (props) => {
          const {data} = props ?? {};

          return  ocrCalculateSimilarity(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OcrCalculateSimilarityMutationResult = NonNullable<Awaited<ReturnType<typeof ocrCalculateSimilarity>>>
    export type OcrCalculateSimilarityMutationBody = OcrCalculateSimilarityBody
    export type OcrCalculateSimilarityMutationError = unknown

    /**
 * @summary Calculate similarity between two images using OCR text
 */
export const useOcrCalculateSimilarity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ocrCalculateSimilarity>>, TError,{data: OcrCalculateSimilarityBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ocrCalculateSimilarity>>,
        TError,
        {data: OcrCalculateSimilarityBody},
        TContext
      > => {

      const mutationOptions = getOcrCalculateSimilarityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    