
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Card, Button, Input, Select, useToastHelpers } from '@x-ear/ui-web';
import { usePaytrInitiate } from '../api/generated/xEarCRMAPIAutoGenerated';
import { CreditCard, Wallet, AlertTriangle, ShieldCheck, Receipt } from 'lucide-react';

export default function PosPage() {
    const [iframeUrl, setIframeUrl] = useState<string | null>(null);
    const [result, setResult] = useState<'success' | 'fail' | null>(null);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    // For standalone payment, we might need to create a temporary sale or have an endpoint that supports direct payment without sale ID?
    // However, the backend 'initiate_paytr_payment' REQUIRES a sale_id.
    // For this 'Tahsilat' page to work as a generic POS, we effectively need a way to link it to a patient or create a "Quick Sale".
    // Since Phase 5 spec says "hasta seçimi (opsiyonel)", but our backend demands a sale_id, 
    // we might need to conditionally handle this.
    // OPTION 1: The backend endpoint `initiate_paytr_payment` checks `sale_id`.
    // If we want a generic POS, we probably need a "Generic Sale" or create a "Deposit" type sale on the fly.
    // Let's assume for now we need to Select a Patient, create a quick 'Deposit' sale, and then pay it.

    // BUT, for now, let's build the UI. If the User tries to pay without a sale, we might hit a backend error.
    // I will mock the flow: UI -> (Create Ghost Sale if needed?) -> Initiate Payment.
    // Actually, to keep it simple and safe: We will ask for a Reference/Note and Amount.
    // In a real app we'd pick a patient.

    const { register, handleSubmit, watch, setValue } = useForm({
        defaultValues: {
            amount: '',
            installment: '1',
            note: '',
            patientName: '' // Simplified for now, just text
        }
    });

    // We can't actually call usePaytrInitiate without a Sale ID based on current backend.
    // I will add a TODO note in the UI.

    const amount = watch('amount');
    const installment = watch('installment');

    // Simulate iframe for UI demo if no real backend support for standalone POS yet
    // OR create a quick sale record in background?
    // Let's stick to the UI implementation requested.

    const onSubmit = async (data: any) => {
        // In a real implementation:
        // 1. Create a "Deposit" sale for the patient (or generic user)
        // 2. Call initiate with that sale_id
        console.log('Starting payment for:', data);
        alert("Bu özellik için backend'de 'Bağımsız Ödeme' endpoint'i veya 'Hızlı Satış Oluşturma' akışı gereklidir. Şu an Sale ID zorunludur.");
    };

    return (
        <div className="max-w-4xl mx-auto py-8 px-4">
            <div className="mb-8">
                <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                    <CreditCard className="w-8 h-8 text-blue-600" />
                    Hızlı Tahsilat
                </h1>
                <p className="text-gray-500 mt-1">
                    Hasta kartına gitmeden hızlı ödeme alma ekranı.
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Payment Form */}
                <div className="lg:col-span-2 space-y-6">
                    <Card className="p-6">
                        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        Ad Soyad / Hasta
                                    </label>
                                    <Input
                                        {...register('patientName')}
                                        placeholder="Müşteri Adı"
                                        className="h-11"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">
                                        İşlem Notu / Açıklama
                                    </label>
                                    <Input
                                        {...register('note')}
                                        placeholder="Örn: Cihaz ön ödemesi"
                                        className="h-11"
                                    />
                                </div>
                            </div>

                            <div className="p-6 bg-blue-50 rounded-xl border border-blue-100 flex flex-col items-center justify-center">
                                <label className="text-blue-800 text-sm font-medium mb-2">
                                    Tahsil Edilecek Tutar
                                </label>
                                <div className="relative w-full max-w-xs">
                                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-bold text-blue-900">₺</span>
                                    <input
                                        type="number"
                                        {...register('amount')}
                                        className="w-full bg-white border-2 border-blue-200 rounded-lg py-3 pl-10 pr-4 text-2xl font-bold text-blue-900 focus:ring-4 focus:ring-blue-200 focus:border-blue-400 outline-none text-center transition-all"
                                        placeholder="0.00"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">Taksit Seçenekleri</label>
                                <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
                                    {[1, 2, 3, 6, 9, 12].map(num => (
                                        <button
                                            key={num}
                                            type="button"
                                            onClick={() => setValue('installment', num.toString())}
                                            className={`py-2 px-1 text-sm font-medium rounded-lg border transition-all ${installment === num.toString()
                                                    ? 'bg-blue-600 text-white border-blue-600 shadow-md'
                                                    : 'bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                                                }`}
                                        >
                                            {num === 1 ? 'Tek Çekim' : `${num} Taksit`}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <Button type="submit" className="w-full h-12 text-lg font-medium shadow-lg shadow-blue-200">
                                Ödemeyi Başlat
                            </Button>

                            <div className="flex items-center justify-center gap-2 text-xs text-gray-400">
                                <ShieldCheck className="w-4 h-4 text-green-500" />
                                <span>256-bit SSL Güvenli Ödeme Altyapısı</span>
                            </div>
                        </form>
                    </Card>
                </div>

                {/* Recent Transactions (Mock for UI) */}
                <div className="space-y-6">
                    <h3 className="text-lg font-semibold text-gray-900 px-1">Son İşlemler</h3>
                    <div className="space-y-3">
                        {[1, 2, 3].map((_, i) => (
                            <div key={i} className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                    <div className={`p-2 rounded-lg ${i === 0 ? 'bg-green-100' : 'bg-gray-100'}`}>
                                        <Wallet className={`w-5 h-5 ${i === 0 ? 'text-green-600' : 'text-gray-500'}`} />
                                    </div>
                                    <div>
                                        <p className="text-sm font-medium text-gray-900">Ahmet Yılmaz</p>
                                        <p className="text-xs text-gray-500">Bugün, 14:30</p>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm font-bold text-gray-900">₺1.250,00</p>
                                    <p className="text-xs text-green-600 font-medium">Başarılı</p>
                                </div>
                            </div>
                        ))}
                    </div>

                    <button className="w-full py-2 text-sm text-blue-600 font-medium hover:bg-blue-50 rounded-lg transition-colors">
                        Tüm İşlemleri Gör
                    </button>
                </div>
            </div>
        </div>
    );
}
