/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCashSummaryParams,
  GetUnifiedCashRecordsParams,
  HTTPValidationError
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * Unified cash records endpoint - returns all financial records from one place.

Combines:
- Sales (satışlar)
- PaymentRecords (ödeme kayıtları)
- Cash Records (nakit kayıtları)
 * @summary Get Unified Cash Records
 */
export const getUnifiedCashRecords = (
    params?: GetUnifiedCashRecordsParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/unified-cash-records`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetUnifiedCashRecordsQueryKey = (params?: GetUnifiedCashRecordsParams,) => {
    return [
    `/api/unified-cash-records`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUnifiedCashRecordsQueryOptions = <TData = Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError = HTTPValidationError>(params?: GetUnifiedCashRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnifiedCashRecordsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnifiedCashRecords>>> = ({ signal }) => getUnifiedCashRecords(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetUnifiedCashRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof getUnifiedCashRecords>>>
export type GetUnifiedCashRecordsQueryError = HTTPValidationError


export function useGetUnifiedCashRecords<TData = Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError = HTTPValidationError>(
 params: undefined |  GetUnifiedCashRecordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnifiedCashRecords>>,
          TError,
          Awaited<ReturnType<typeof getUnifiedCashRecords>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUnifiedCashRecords<TData = Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError = HTTPValidationError>(
 params?: GetUnifiedCashRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnifiedCashRecords>>,
          TError,
          Awaited<ReturnType<typeof getUnifiedCashRecords>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUnifiedCashRecords<TData = Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError = HTTPValidationError>(
 params?: GetUnifiedCashRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Unified Cash Records
 */

export function useGetUnifiedCashRecords<TData = Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError = HTTPValidationError>(
 params?: GetUnifiedCashRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnifiedCashRecords>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetUnifiedCashRecordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Financial summary information.

Query parameters:
- period: summary period (today, week, month, year)
- start_date, end_date: custom date range
 * @summary Get Cash Summary
 */
export const getCashSummary = (
    params?: GetCashSummaryParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/unified-cash-records/summary`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetCashSummaryQueryKey = (params?: GetCashSummaryParams,) => {
    return [
    `/api/unified-cash-records/summary`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCashSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getCashSummary>>, TError = HTTPValidationError>(params?: GetCashSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCashSummaryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCashSummary>>> = ({ signal }) => getCashSummary(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCashSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getCashSummary>>>
export type GetCashSummaryQueryError = HTTPValidationError


export function useGetCashSummary<TData = Awaited<ReturnType<typeof getCashSummary>>, TError = HTTPValidationError>(
 params: undefined |  GetCashSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCashSummary>>,
          TError,
          Awaited<ReturnType<typeof getCashSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCashSummary<TData = Awaited<ReturnType<typeof getCashSummary>>, TError = HTTPValidationError>(
 params?: GetCashSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCashSummary>>,
          TError,
          Awaited<ReturnType<typeof getCashSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCashSummary<TData = Awaited<ReturnType<typeof getCashSummary>>, TError = HTTPValidationError>(
 params?: GetCashSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Cash Summary
 */

export function useGetCashSummary<TData = Awaited<ReturnType<typeof getCashSummary>>, TError = HTTPValidationError>(
 params?: GetCashSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCashSummary>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCashSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




