/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * X-Ear CRM API
 * Auto-generated from Flask backend routes
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListAuditParams
} from '.././schemas';

import { adminApi } from '../../apiMutator';




/**
 * List audit logs with optional filters
 * @summary List Audit
 */
export const listAudit = (
    params?: ListAuditParams,
 signal?: AbortSignal
) => {
      
      
      return adminApi<unknown>(
      {url: `/api/audit`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListAuditQueryKey = (params?: ListAuditParams,) => {
    return [
    `/api/audit`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAuditQueryOptions = <TData = Awaited<ReturnType<typeof listAudit>>, TError = HTTPValidationError>(params?: ListAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAuditQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAudit>>> = ({ signal }) => listAudit(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListAuditQueryResult = NonNullable<Awaited<ReturnType<typeof listAudit>>>
export type ListAuditQueryError = HTTPValidationError


export function useListAudit<TData = Awaited<ReturnType<typeof listAudit>>, TError = HTTPValidationError>(
 params: undefined |  ListAuditParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAudit>>,
          TError,
          Awaited<ReturnType<typeof listAudit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAudit<TData = Awaited<ReturnType<typeof listAudit>>, TError = HTTPValidationError>(
 params?: ListAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAudit>>,
          TError,
          Awaited<ReturnType<typeof listAudit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAudit<TData = Awaited<ReturnType<typeof listAudit>>, TError = HTTPValidationError>(
 params?: ListAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Audit
 */

export function useListAudit<TData = Awaited<ReturnType<typeof listAudit>>, TError = HTTPValidationError>(
 params?: ListAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAudit>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListAuditQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




