import * as React from 'react';
import { useState } from 'react';
import { Bug, ChevronDown, Check, Loader2, Shield } from 'lucide-react';
import { useAdminDebugAvailableRoles, useAdminDebugSwitchRole, getAdminDebugAvailableRolesQueryKey } from '../../api/generated/xEarCRMAPIAutoGenerated';
import { useAuthStore } from '../../stores/authStore';
import { AUTH_TOKEN, REFRESH_TOKEN } from '../../constants/storage-keys';

// Debug rol switcher sadece admin@x-ear.com için gösterilir
const DEBUG_ADMIN_EMAIL = 'admin@x-ear.com';

interface DebugRoleSwitcherProps {
  darkMode?: boolean;
}

export const DebugRoleSwitcher: React.FC<DebugRoleSwitcherProps> = ({ darkMode = false }) => {
  const { user, setUser } = useAuthStore();
  const [isOpen, setIsOpen] = useState(false);
  
  // Check if current user is the debug admin
  const isDebugAdmin = user?.email === DEBUG_ADMIN_EMAIL;
  
  // Fetch available roles only if debug admin
  const { data: rolesResponse, isLoading: rolesLoading } = useAdminDebugAvailableRoles({
    query: {
      queryKey: getAdminDebugAvailableRolesQueryKey(),
      enabled: isDebugAdmin,
      staleTime: 5 * 60 * 1000, // 5 dakika
    }
  });
  
  // Role switch mutation
  const { mutate: switchRole, isPending: isSwitching } = useAdminDebugSwitchRole({
    mutation: {
      onSuccess: (response) => {
        const data = response?.data?.data;
        if (data) {
          // Token'ları localStorage'a yaz
          if (data.accessToken) {
            localStorage.setItem(AUTH_TOKEN, data.accessToken);
            window.__AUTH_TOKEN__ = data.accessToken;
          }
          if (data.refreshToken) {
            localStorage.setItem(REFRESH_TOKEN, data.refreshToken);
          }
          
          // User state'i güncelle - effective role'u user.role olarak kullan
          if (user && data.effectiveRole) {
            setUser({
              ...user,
              role: data.effectiveRole,
            });
          }
          
          // Sayfayı yenile - tüm permission kontrollerinin güncel olması için
          window.location.reload();
        }
      },
      onError: (error) => {
        console.error('Role switch failed:', error);
        alert('Rol değiştirme başarısız oldu');
      }
    }
  });
  
  // Debug admin değilse hiçbir şey gösterme
  if (!isDebugAdmin) {
    return null;
  }
  
  const roles = rolesResponse?.data?.data?.roles || [];
  const currentRole = user?.role || 'unknown';
  
  const handleRoleSwitch = (roleName: string) => {
    if (roleName === currentRole) {
      setIsOpen(false);
      return;
    }
    
    switchRole({
      data: { targetRole: roleName }
    });
    setIsOpen(false);
  };
  
  return (
    <div style={{ position: 'relative' }}>
      {/* Debug Badge & Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        disabled={isSwitching || rolesLoading}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          padding: '0.5rem 0.75rem',
          borderRadius: '0.5rem',
          border: `2px solid ${darkMode ? '#f59e0b' : '#d97706'}`,
          backgroundColor: darkMode ? '#451a03' : '#fef3c7',
          color: darkMode ? '#fbbf24' : '#92400e',
          fontSize: '0.75rem',
          fontWeight: '600',
          cursor: 'pointer',
          transition: 'all 0.2s ease',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.backgroundColor = darkMode ? '#78350f' : '#fde68a';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.backgroundColor = darkMode ? '#451a03' : '#fef3c7';
        }}
      >
        {isSwitching ? (
          <Loader2 size={14} className="animate-spin" />
        ) : (
          <Bug size={14} />
        )}
        <span>Debug: {currentRole}</span>
        <ChevronDown size={12} style={{
          transform: isOpen ? 'rotate(180deg)' : 'rotate(0)',
          transition: 'transform 0.2s ease'
        }} />
      </button>
      
      {/* Dropdown */}
      {isOpen && (
        <div
          style={{
            position: 'absolute',
            top: '100%',
            right: 0,
            marginTop: '0.5rem',
            minWidth: '220px',
            backgroundColor: darkMode ? '#1f2937' : '#ffffff',
            border: `1px solid ${darkMode ? '#374151' : '#e5e7eb'}`,
            borderRadius: '0.5rem',
            boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.2)',
            zIndex: 1001,
          }}
        >
          {/* Header */}
          <div style={{
            padding: '0.75rem 1rem',
            borderBottom: `1px solid ${darkMode ? '#374151' : '#e5e7eb'}`,
            backgroundColor: darkMode ? '#111827' : '#f9fafb',
            borderRadius: '0.5rem 0.5rem 0 0',
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              color: darkMode ? '#fbbf24' : '#d97706',
              fontWeight: '600',
              fontSize: '0.75rem',
            }}>
              <Shield size={14} />
              <span>QA Rol Değiştirici</span>
            </div>
            <div style={{
              fontSize: '0.65rem',
              color: darkMode ? '#9ca3af' : '#6b7280',
              marginTop: '0.25rem',
            }}>
              Sadece {DEBUG_ADMIN_EMAIL} kullanabilir
            </div>
          </div>
          
          {/* Role List */}
          <div style={{ padding: '0.5rem 0' }}>
            {rolesLoading ? (
              <div style={{
                padding: '1rem',
                textAlign: 'center',
                color: darkMode ? '#9ca3af' : '#6b7280',
                fontSize: '0.875rem',
              }}>
                <Loader2 size={20} className="animate-spin" style={{ marginBottom: '0.5rem' }} />
                <div>Roller yükleniyor...</div>
              </div>
            ) : roles.length === 0 ? (
              <div style={{
                padding: '1rem',
                textAlign: 'center',
                color: darkMode ? '#9ca3af' : '#6b7280',
                fontSize: '0.875rem',
              }}>
                Rol bulunamadı
              </div>
            ) : (
              roles.map((role) => {
                const roleName = role.name || '';
                const isCurrentRole = roleName === currentRole;
                return (
                  <button
                    key={roleName}
                    onClick={() => roleName && handleRoleSwitch(roleName)}
                    disabled={isSwitching || !roleName}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      width: '100%',
                      padding: '0.625rem 1rem',
                      border: 'none',
                      backgroundColor: isCurrentRole
                        ? (darkMode ? '#1d4ed8' : '#dbeafe')
                        : 'transparent',
                      color: isCurrentRole
                        ? (darkMode ? '#ffffff' : '#1e40af')
                        : (darkMode ? '#ffffff' : '#1f2937'),
                      textAlign: 'left',
                      fontSize: '0.875rem',
                      cursor: isSwitching ? 'not-allowed' : 'pointer',
                      transition: 'background-color 0.2s ease',
                    }}
                    onMouseEnter={(e) => {
                      if (!isCurrentRole) {
                        e.currentTarget.style.backgroundColor = darkMode ? '#374151' : '#f3f4f6';
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!isCurrentRole) {
                        e.currentTarget.style.backgroundColor = 'transparent';
                      }
                    }}
                  >
                    <div>
                      <div style={{ fontWeight: isCurrentRole ? '600' : '500' }}>
                        {role.displayName}
                      </div>
                      {role.permissionCount !== undefined && (
                        <div style={{
                          fontSize: '0.7rem',
                          color: darkMode ? '#9ca3af' : '#6b7280',
                          marginTop: '0.125rem',
                        }}>
                          {role.permissionCount} izin
                        </div>
                      )}
                    </div>
                    {isCurrentRole && (
                      <Check size={16} style={{
                        color: darkMode ? '#ffffff' : '#1d4ed8',
                      }} />
                    )}
                  </button>
                );
              })
            )}
          </div>
          
          {/* Footer */}
          <div style={{
            padding: '0.5rem 1rem',
            borderTop: `1px solid ${darkMode ? '#374151' : '#e5e7eb'}`,
            backgroundColor: darkMode ? '#111827' : '#f9fafb',
            borderRadius: '0 0 0.5rem 0.5rem',
            fontSize: '0.65rem',
            color: darkMode ? '#6b7280' : '#9ca3af',
          }}>
            Rol değişince sayfa yenilenir
          </div>
        </div>
      )}
    </div>
  );
};

export default DebugRoleSwitcher;
